### ISSUE TITLE
Problems with non-json data.

### ISSUE THREAD

**Issue by ballPointPenguin** [ember-cli/ember-ajax#1]
I was attempting to use ember-json for a POST with FormData (Content-Type:multipart/form-data) for a file upload operation. Unfortunately, ember-ajax overrides the contentType and also passes the data through JSON.stringify.

https://github.com/ember-cli/ember-ajax/blob/master/addon/services/ajax.js#L132

Perhaps there can be an option to disable this feature or maybe disable it automatically if options.dataType or options.contentType are set to something other than json.

If not, then the documentation should clearly state that this service is designed ONLY for json data.

**Comment by taras** [comment]
I agree that `ember-ajax` should not enforce payload to be in JSON format. I rarely work with non JSON data, so I don't have much personal experience with that uses case. I would like to take some time on deciding how to add this to the library(PRs are welcome, as I see you've done already in #2 ).

**Comment by abuiles** [comment]
This is fixed by #5

**Comment by ballPointPenguin** [comment]
thanks, @abuiles
