### ISSUE TITLE
JSON API Serialization  

### ISSUE THREAD

**Issue by paublyrne** [ember-cli/ember-ajax#102]
I am using json_api, and not getting the expected format when I do a post with Ember Ajax.

I figure the add-on should serialize my data if I set the right Content-Type. Is that right? Or do I need to structure the data I pass to ajax.post myself? I can do that no problem, but I suspect that's not the right approach.

So I'm making a post like this.
```
    ajax.post(ENV.API_ENDPOINT + 'line_items', {
      headers: {
        'Content-Type': 'application/vnd.api+json',
        'Accept': 'application/vnd.api+json'
      },
      data: {
        cart_id: cart.id,
        product_id: product.id,
        quantity: 1
      }
```
And it sending a request like this: 
```
{
  "cart_id": "1160",
  "product_id": "57",
  "quantity": 1
}
```
But what I expect is:
```
{
  "data": {
    "attributes": {
      "cart_id": 1,
      "product_id": 57,
      "quantity": 1
    },
    "relationships": {
      "cart": {
        "data": null
      },
      "product": {
        "data": null
      },
    },
    "type": "line-items"
  }
}
```
Is the problem with me? :p

**Comment by alexlafroscia** [comment]
> Is the problem with me? :p

I wouldn't say that, but you're a bit mistaken about what `ember-ajax` is meant to do 😉 

We don't change your data at all, so the request will be made with literally whatever `data` attribute you provide.  I feel like automatically re-formatting the content is a pretty dangerous game to play.  Principle of Least Surprise and all that, you know?

**Comment by paublyrne** [comment]
Thanks Alex - eventually figured this was the case, and put it in the structure I wanted manually. Thanks for the reply!

**Comment by alexlafroscia** [comment]
Sure thing.  I wish that was something that we could help more with, but that would get into a level of serializers and adapters that just isn't part of the Ember AJAX roadmap at this point.  I'll keep it in the back of my mind going forward, though!
