### ISSUE TITLE
Question: How can I access response headers? 

### ISSUE THREAD

**Issue by cqcsobreyra** [ember-cli/ember-ajax#103]
Our backend passes certain information through response headers that we need to be able to see/use on our ember application.

I see support for raw requests were removed, and I don't see anywhere that the full jqXHR is exposed.

Was there a philosophical reasoning behind this? Is there a workaround?

**Comment by alexlafroscia** [comment]
You can still do `raw`!  The code is right here:

https://github.com/ember-cli/ember-ajax/blob/c0028c5ce183035678fde0cf56d32750bcaef464/addon/ajax-request.js#L71-L100

You should get back the raw `XHR` object to access the headers that way.

**Comment by cqcsobreyra** [comment]
Thank you! I'm on 0.7.1 getting the raw deprecation warnings, and didn't see much mention on the readme docs.

**Comment by alexlafroscia** [comment]
Oh, okay! `raw` isn't going away any time soon, so that's the way to go.
