### ISSUE TITLE
Allow calling _super in init

### ISSUE THREAD

**Issue by iezer** [ember-cli/ember-ajax#106]
Right now, if we add a Mixin to all instances of `Ember.Service`, and one of those Mixins has an `init()` function, that `init()` function will never get called by instances of `AjaxService`. 

Example:
```js
let UsefulMixin = Ember.Mixin.extend({
  init() {
    // will never run in AjaxService
    this._pendingThings = [];
  },
  willDestroy() {
    // this will error if init is never run, in particular when AjaxService is torn down
    this._pendingThings.forEach(pendingThing => pendingThing.cancel());
 }
});

Ember.Service.reopen(UsefulMixin);
```

I believe the issue is [here](https://github.com/ember-cli/ember-ajax/blob/master/addon/ajax-request.js#L51-L56) because the code does not call `this._super(...arguments);`. The class will probably have to refactored to be a normal Mixin or Service so that this is possible, rather than an ES6 class.

**Comment by taras** [comment]
We might consider making descend from Ember Object. Before we do, we can try calling `this._super`. Something like this: 

```
...
init() {
  if (this._super) {
   this._super(...arguments);
  }
}
...
```

@alexlafroscia what do you think?

**Comment by rwjblue** [comment]
The current ES6 class system is fairly confusing.  Do we intend for folks to create their own instances of `ember-ajax/ajax-request` via `new AjaxRequest()`?  It seems like we could make this extend from `Ember.Object` and remove the need for `ember-mixinify-class`.

I think it is also likely that we can support the existing API (if we support `var ajax = new AjaxRequest()`) since you can instantiate `Ember.Object`'s that way also...

**Comment by taras** [comment]
That's a good point. We'll look into this further.

**Comment by alexlafroscia** [comment]
So, if I remember right, the reason we went with an ES6 class was that using the `ic-ajax`-inspired `raw` and `request` "standalone" functions required and instance of the AJAX service to be created just for that usage, and it didn't make sense to instantiate a service inside a function that was never meant to be injected like a service normally would. So yes, the idea was for `new AjaxReqest()` to be usable if that's what someone needed, and in fact we use that ourselves here.

We could definitely move to `Ember.Object` instead, if that makes more sense.  However, I'm not sure how to apply the same implementation to both the `Ember.Object` and `Ember.Service`, unless we just make the main implementation a mixin (which might be fine).

**Comment by rwjblue** [comment]
Right, I would make the base implementation a mixin (which is roughly how it is used anyways). Then we can create it from the raw function (mixed into an Ember.Object), and also export from app/services/ajax.js mixed into Ember.Service.

**Comment by alexlafroscia** [comment]
Cool, I can start working on that.
