### ISSUE TITLE
Namespace for a Single Request

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-ajax#111]
I have a legacy end point that lives at the root namespace of my API (e.g. `/users/signout`) whereas every other request lives in a specific namespace (e.g. `/api/`).

It'd be really nice to be able to temporarily override the namespace for some requests, so that I could do something like:

```javascript
this.get('ajax').del('/users/signout', { namespace: '/' });
```

Where the Ajax service is set to use `/api` globally.

**Comment by jherdman** [comment]
My current work around is the following:

```javascript
let ajax = this.get('ajax');
ajax.set('namespace', '/');

ajax.del(....).finally(() => {
  ajax.set('namespace', '/api');
});
```

For this specific use case I'm in the clear, but given that AjaxService is a singleton, it's possible in other use cases this namespace switch may cause requests to go to the wrong namespace.

**Comment by alexlafroscia** [comment]
Great idea! Sorry this was overlooked; I'll put a PR together to allow the `namespace` as an option to the request methods.
