### ISSUE TITLE
Getting Undefined in error function

### ISSUE THREAD

**Issue by paul42** [ember-cli/ember-ajax#124]
I'm probably doing something wrong, but just wondering if someone can point me in the right direction - I don't know what exactly is going wrong, but I don't see any requests coming into my other api. I have app config working my ember-data DS.RestAdapter.

are there any restrictions to using the ajax service in a controller or a component? Can ember-ajax only be used in routes? (if so, do you know what the ember-way is to make ad-hoc posts to get back tokens, without involving ember-data models and pretending I have an active record?)

Thanks in advance

````
//app/serivces/ajax.js
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';
import config from '../config/environment';

export default AjaxService.extend({
  // namespace: '/api/',
  host: config.APP.API_HOST,
  session: Ember.inject.service(),
  headers: Ember.computed('session.data.authenticated.jwt', function(){
    return {
      'Authorization': `Bearer ${this.get('session.data.authenticated.jwt')}`
    }
  })
});
````

````
//app/controllers/givings/new.js
import Ember from 'ember';
import toFixed from 'accounting/to-fixed';
import moment from 'moment';

export default Ember.Controller.extend({
  ajax: Ember.inject.service(),
  actions:{
    sendRequest() {

      const ajax = this.get('ajax');
      let note = this.get('model.lineItems').mapBy('itemDescription').join(', ');
      let total = this.get('model.lineItems').reduce(function(previousValue, item){
        let amount = item.get('itemAmount');
        let newTotal = parseFloat(previousValue) + parseFloat(amount);
        return toFixed(newTotal, 2);
      },0.00);
      let data = {
        "church": this.get('model.church.id'),
        "date": moment(),
        "givingAmount": total,
        "note": note,
        "lineItems": this.get('model.lineItems')
      };
      return ajax.post('/newGiving', { data: data }).then(function(response){
        Ember.Logger.info('response');
        Ember.Logger.info(response);
        return response;
      }).catch(function(error){
        Ember.Logger.info('error');
        Ember.Logger.info(error);
        return error;
      });
    }

  }
  });
````

````
//app/components/new-giving.hbs
 {{#paper-button onClick=(action sendRequest)}}Send Request {{/paper-button}}
````

**Comment by alexlafroscia** [comment]
is your `sendRequest` method being called?  Also, how is the title related to your issues?

**Comment by paul42** [comment]
Yes, the logging in send request works. I'm concerned because the error is coming back undefined, and I can't trouble shoot why the Ajax call is not going through

**Comment by alexlafroscia** [comment]
Oh, so the argument to the `.catch` callback is undefined? That's interesting... And definitely shouldn't be happening. 

What's the response from the server?

**Comment by paul42** [comment]
unfortunately I'm running the node server in another terminal and there is no incoming request at all. there is zero incoming requests when I punch the send request button :/ I can make the other calls using ember-data and I do see the incoming / outgoing request logs.
I was sort of hoping someone had seen it before or could give me any pointers to look for, since I'm pretty certain it's my code (I made a whole new project, did just ember-ajax, and aimed it at the endpoint and it worked). I tried just doing Ember.$.ajax and I get a weird _platform undefined error.

**Comment by alexlafroscia** [comment]
Honestly, I have no idea... Sorry I can't be more help.  Can you check out the Network inspector and see if there is a request being made from the client?  Maybe it's just not hitting your backend correctly.

**Comment by paul42** [comment]
Good idea. I'll check that out.

**Comment by alexlafroscia** [comment]
My thought it that your `host` or `namespace` might be mis-configured, thus causing a weird problem where the request is being made into the ether and creating that weird error case you're seeing.

If that is what's happening, I would love if you could provide more context about what you're seeing happen so that Ember AJAX can respond with a more useful error message.  Maybe we can do a Screenhero session in hopes of making that better.

**Comment by alexlafroscia** [comment]
Hey @paul42! Were you able to validate what the error here was?  If you were able to resolve the problem I would love to close this issue, and if there are changes that need to be make to `ember-ajax` then I'd love to do that, too!

**Comment by paul42** [comment]
hey @alexlafroscia thanks for circling back around, but I've shelved this project due to other issues - it was almost certainly my code somewhere, but thanks for the great followthrough
