### ISSUE TITLE
If payload evaluates falsey but is not null or undefined, don't transform payload. 

### ISSUE THREAD

**Issue by SteelBurgher** [ember-cli/ember-ajax#125]
This line from ajax-request.js reassigns a payload like the number 0 to an object. 
`payload = payload || {};`

Although you can make the solid argument that api responses should follow specifications like JSON-API, and never simply return numbers, if a developer wishes to send a response this way, I think it's worthwhile for ember-ajax to accommodate that.

**Comment by alexlafroscia** [comment]
Absolutely. I saw you filed a PR; I'm happy to accept it given tests are added and they all pass!

**Comment by alexlafroscia** [comment]
Closed by #126

**Comment by manoharank** [comment]
Upgrading to `2.5.0` from `0.7.1`. #126 breaks my app, I expect a null value from the API, but now this returns an empty object, which breaks all my `{{#if data}}`.

**Comment by manoharank** [comment]
cc @alexlafroscia

**Comment by taras** [comment]
@manoharank can you please open a separate issue for this?

**Comment by manoharank** [comment]
@taras sure
