### ISSUE TITLE
3rd party API calls cannot be mocked with Pretender when using ember-ajax

### ISSUE THREAD

**Issue by sstgithub** [ember-cli/ember-ajax#131]
Pretender is not able to mock 3rd party API calls i.e ones with full web addresses if using ember-ajax. I assume this is an issue with ember-ajax since this does work when you forego ember-ajax and just wrap jQuery AJAX  in a RSVP promise yourself.

**Example:**

_Test code_:

```
let server = Pretender.new()

this.server.get('https://api.ipify.org', function() {
   return [200, { 'Content-Type': 'application/json' }, JSON.stringify({"ip": "123"})];
});
```

_Application code with ember ajax (does not work)_:

This never gets handled by Pretender and results in `called set on destroyed object`

```
return this.get('ajax').get('https://api.ipify.org', function() {
   datatype: 'jsonp',
}.then((value) => {
...
}
```

_Application code with jQuery Ember AJAX wrapped in Ember RSVP Promise (works)_:

```
return new Ember.RSVP.Promise((resolve, reject) => {
    Ember.$.ajax({
        url: 'https://api.ipify.org',
        datatype: 'jsonp',
        method: 'GET'
    })
    .done((ip) => {
        ...
     });
});
```

**Tested with:**
Ember v2.5.0
Ember CLI v2.5.0
Ember AJAX v2.4.1
Pretender v1.1.0
Ember QUnit v1.4.0

**Comment by taras** [comment]
Try using type: 'jsonp' instead of datatype

**Comment by alexlafroscia** [comment]
Hey @sstgithub! Were you able to get this resolved?  I don't think `ember-ajax` can do anything to mess with Pretender, so I think it's unlikely that the issue is actually with `ember-ajax`.  I'd like to close the issue if that's the case, but want to make sure that you found a solution first (or at least to verify that this addon isn't the cause).

**Comment by sstgithub** [comment]
Hey @alexlafroscia! I probably won't have time to reproduce this for a little while so I'm going to go ahead and close it for now. I will re-open and add more information later if I can reproduce it.
