### ISSUE TITLE
Not able to request html documents.

### ISSUE THREAD

**Issue by arenoir** [ember-cli/ember-ajax#132]
Perhaps this should not be supported but I have run into this issue while upgrading from ic-ajax.

In my application I fetch some server side html content (mostly for printing and reporting purposes). 

Example.
```
    return this.get('ajax').request(url, {
      data: data,
      method: 'GET',
      headers: {
        'auth-token': authToken,
        'Content-Type': 'text/html; charset=utf-8',
        'Accept': 'text/html'
      }
    });
```

Errors out.
```
SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at jQuery.parseJSON (vendor.js:8282:14)
    at ajaxConvert (vendor.js:8564:19)
    at done (vendor.js:9025:15)
    at XMLHttpRequest.<anonymous> (vendor.js:9441:9)
```

I understand that this may be a misuse of ember-ajax as it may be intended just to request json payload.   Any suggestions are appreciated.

**Comment by taras** [comment]
You should be able to do it with raw. Have you tried that?

--
Taras Mankovski





On Tue, Jul 12, 2016 at 6:27 PM -0400, "Aaron Renoir" <notifications@github.com> wrote:












Perhaps this should not be supported but I have run into this issue while upgrading from ic-ajax.



In my application I fetch some server side html content (mostly for printing and reporting purposes). 



Example.

    return this.get('ajax').request(url, {
      data: data,
      method: 'GET',
      headers: {
        'auth-token': authToken,
        'Content-Type': 'text/html; charset=utf-8',
        'Accept': 'text/html'
      }
    });




Errors out.

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at jQuery.parseJSON (vendor.js:8282:14)
    at ajaxConvert (vendor.js:8564:19)
    at done (vendor.js:9025:15)
    at XMLHttpRequest.<anonymous> (vendor.js:9441:9)




I understand that this may be a misuse of ember-ajax as it may be intended just to request json payload.   Any suggestions are appreciated.

**Comment by arenoir** [comment]
Same error with raw.

```
    return this.get('ajax').raw(url, {
      data: data,
      method: 'GET',
      headers: {
        'auth-token': authToken,
        'Content-Type': 'text/html; charset=utf-8',
        'Accept': 'text/html'
      }
    });

```

**Comment by arenoir** [comment]
It is a bug in [here](https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-request.js#L410).  jquey ajax will determine the dataType from the response header Content-Type.  Because ember-ajax sets it to json if not specified it was trying to parse html as json.

Workaround add dataType.

return this.get('ajax').raw(url, {
      data: data,
      method: 'GET',
      dataType: 'html',
      headers: {
        'auth-token': authToken,
        'Content-Type': 'text/html; charset=utf-8',
        'Accept': 'text/html'
      }
    });

**Comment by arenoir** [comment]
Not a bug just a change of the default.  I was thrown off by the headers option.  The `dataType` option will add the appropriate 'Accept' header but not the other way around.
