### ISSUE TITLE
How to abort requests made by ember-ajax?

### ISSUE THREAD

**Issue by fpauser** [ember-cli/ember-ajax#133]
As `jqXHR` is only available _after_ a request is finished there seems to be no possibility to cancel running requests - or did I miss something?

**Comment by alexlafroscia** [comment]
No, didn't miss anything.  At the moment, this isn't something we plan to support because, AFAIK, the `fetch` API also doesn't support it.  We've been trying to avoid anything that isn't available in `fetch` since the long-term plan is to move to using that under the hood instead of jQuery AJAX.
