### ISSUE TITLE
Access in utilities

### ISSUE THREAD

**Issue by knownasilya** [ember-cli/ember-ajax#134]
I can't find a way to access ember-ajax inside a utility. Is this possible, if not, why? This requires me to either wrap `Ember.$.ajax` or include `ic-ajax` or some other library. Seems wasteful.

**Comment by rwjblue** [comment]
You can definitely do a raw request (without the service). It should be documented in the README, is it not?

**Comment by rwjblue** [comment]
`import raw from 'ember-ajax/raw';`

**Comment by alexlafroscia** [comment]
Using `raw` returns the jqXHR directly; you can also use `request` the same way which behaves the same way as the service.

**Comment by rwjblue** [comment]
Gotcha, thanks @alexlafroscia!

@knownasilya would definitely love some documentation help here, I do not see this in the README..

**Comment by alexlafroscia** [comment]
Yeah, we'll definitely work together on #135 to get some better documentation in the README about using the request-making without a service.
