### ISSUE TITLE
2.5.0 introduced a breaking change

### ISSUE THREAD

**Issue by thomblake** [ember-cli/ember-ajax#141]
Updating from 2.4.1 to 2.5.0 broke our error handling since `details` was changed to `meta` in the error response.

**Comment by alexlafroscia** [comment]
Oops, sorry about that!  Let me get a 2.5.1 out real quick that aliases the two and throws a deprecation warning.

**Comment by alexlafroscia** [comment]
Actually, scratch that; I'm just going to revert it to `details` and we can change the property to `meta` later on if we want.
