### ISSUE TITLE
Allow boolean contentType values within the options hash.

### ISSUE THREAD

**Issue by jrowlingson** [ember-cli/ember-ajax#143]
The jQuery.ajax options hash accepts a contentType of type [Boolean or String](http://api.jquery.com/jQuery.ajax/). If the contentType is set to `false` it is [reassigned](https://github.com/ember-cli/ember-ajax/blob/b4bf0f28e84b6ea3fe7737f80ce9abf34944bcd5/addon/mixins/ajax-request.js#L424) with the default content type of `'application/x-www-form-urlencoded; charset=UTF-8'`. We should check for the existence of the contentType key in the options hash instead and avoid reassigning if it has been set.

We have an issue where we need to pass a contentType with a value of `false` in order to coerce jQuery into setting the required `boundary` parameter for the `multipart/form-data` content type. See http://stackoverflow.com/a/8244082.

Related: https://github.com/ember-cli/ember-ajax/pull/116

**Comment by alexlafroscia** [comment]
Hmm, interesting.  I'll take a look into this when I get a chance (probably sometime this week) but a PR to add the support you're looking for would be welcome and appreciated!
