### ISSUE TITLE
errors passing to AjaxError while instantiating

### ISSUE THREAD

**Issue by keradus** [ember-cli/ember-ajax#145]
Hi !

While instantiating the subclass of `AjaxError` the `errors` payload of the request is always passed, eg:
https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-request.js#L526

But in some cases, the data is not received in constructor, eg:
https://github.com/ember-cli/ember-ajax/blob/master/addon/errors.js#L105-L107

why is that?

**Comment by alexlafroscia** [comment]
Closed by #173 (this was an oversight)
