### ISSUE TITLE
2.5.1 broke POST upload file

### ISSUE THREAD

**Issue by seymores** [ember-cli/ember-ajax#147]
Upgraded to latest ember 2.7 and ember-ajax to 2.5.1.
Immediately the file upload is not working anymore.

Error message seen in the console was missing 'Access-Control-Allow-Origin'.
Checked with previous version and sure enough  'Access-Control-Allow-Origin' was sent out in the request header but not in the latest 2.5.1.

Is there a config change to contentType that effects the missing 'Access-Control-Allow-Origin'?
We were using 'multipart/form' and the latest version doesn't seems to support multipart/form?

**Comment by alexlafroscia** [comment]
Hmm, I'll have to check it out.  In the meantime, if you want to help speed a fix along, submitting a PR with a failing test case will really help me out!

**Comment by lifeart** [comment]
Same Err, but because multipart/form-data; now not default

**Comment by jrowlingson** [comment]
@lifeart correct - the fix is on master

**Comment by alexlafroscia** [comment]
@jrowlingson @lifeart So cutting a new 2.5.2 release is all we need? That's an easy fix ;)

**Comment by jherdman** [comment]
2.5.2 is released, and I can verify that it's resolved the issue.
