### ISSUE TITLE
Why ember-ajax traverse the array response?

### ISSUE THREAD

**Issue by manoharank** [ember-cli/ember-ajax#157]
I don't know the reason behind the loop below for the success response (which is an array). Is that intentional? cc @alexlafroscia 

https://github.com/ember-cli/ember-ajax/blob/19807d82e59be7796db20cedc79c1bb69685dcb2/addon/mixins/ajax-request.js#L834

**Comment by taras** [comment]
@manoharank yes, this does look a bit strange. 

@alexlafroscia do you remember why this treats every returned object as an error?

**Comment by alexlafroscia** [comment]
Hmmm... I think we were doing some work with how we normalize responses.  To be honest -- it's confusing and I don't really like how we're doing it.

I think we should probably think through a better approach for this and release a major version that cleans that up a bunch.

**Comment by alexlafroscia** [comment]
The goal for this code was to normalize error responses.  We've realized that this is a bad idea and will be changing this behavior.  See #175 for progress.
