### ISSUE TITLE
$.parseJSON deprecation

### ISSUE THREAD

**Issue by jcbvm** [ember-cli/ember-ajax#159]
With jquery 3+, `$.parseJSON` is deprecated, they suggest to just use `JSON.parse`. Is there any reason why the jquery method is used instead of just `JSON.parse`?

**Comment by taras** [comment]
@jcbvm it's probably an oversight. Can you create a PR with this change?

**Comment by jcbvm** [comment]
@taras see https://github.com/ember-cli/ember-ajax/pull/160

**Comment by alexlafroscia** [comment]
Closed by #160
