### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-ajax#163]
`ember-cli-code-coverage` now [supports addons](https://github.com/kategengler/ember-cli-code-coverage/pull/31) so I want to get that running for `ember-ajax`.

**Comment by rwjblue** [comment]
Please keep me posted if you run into issues...

**Comment by alexlafroscia** [comment]
Will do! Going to try this out tonight.

**Comment by alexlafroscia** [comment]
@rwjblue Two issues off the bat:

1. Console logging slipped through the cracks (although it seems like [that was taken care of already](https://github.com/kategengler/ember-cli-code-coverage/pull/35))
2. After doing `COVERAGE=true ember test` the tests all run, but the process doesn't exit.

Going to dig into the latter problem and see if I can figure out what's up.

**Comment by alexlafroscia** [comment]
We've had coverage for a while, so this should be closed.
