### ISSUE TITLE
POST and PUT Requests Broken with Ember Data + AjaxSupport

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-ajax#169]
POST and PUT requests with Ember Data normally work via sending a JSON formatted request body. When mixing in the AjaxSupport module, both use POST style params (e.g. `foo=bar&baz=quq`).

Setting the content-type default does not resolve the issue.

Before
-------

![screen shot 2016-10-05 at 9 49 49 am](https://cloud.githubusercontent.com/assets/3300/19115761/254b1a58-8ae1-11e6-9407-13e272244b85.png)

After
-----

![screen shot 2016-10-05 at 9 51 33 am](https://cloud.githubusercontent.com/assets/3300/19115815/50e08446-8ae1-11e6-855a-c47caddacf8a.png)

Additional Details
------------------

* Ember Data version 2.8
* Ember Ajax b32b9ee5ede69e09a162eb98d354f7de6297f679

**Comment by jherdman** [comment]
I think there's a broader relationship problem between Ember Data adapters and Ember Ajax. A lot of what the Ajax Request mixin does is what ED's Adapters do. The usage of Adapters allows for users to specialize how they handle response contents (e.g. at my company we look for certain headers and handle them with services).

Perhaps it'd be wise to consider extracting success and failure handling to an adapter layer of our own, and thus let us proxy to ED's with the Ajax Support mixin?

**Comment by alexlafroscia** [comment]
I think at this point I'm in favor of just dropping this mixin. It's caused a lot of trouble and I don't think it's actually that useful.  Eventually, the plan is (was?) to replace the network calls in Ember adapters with `ember-ajax` instead (or to have the adapters consume `ember-ajax`, something like that) but we never got all the way there.

There's going to be a meeting this week to plan out `ember-ajax`'s future so we'll figure out what we want to do about this mixin there.
