### ISSUE TITLE
Globally inject the ajax service into your route or component 

### ISSUE THREAD

**Issue by rinoldsimon** [ember-cli/ember-ajax#174]
How to Globally inject the ajax service `ajax: Ember.inject.service()` into your route or component or controller? Is it possible to create `initializer` ? Eg:
```
export function initialize( application ) {
	application.inject('controller', 'ajax', 'service');
	application.inject('component', 'ajax', 'service');
	application.inject('route', 'ajax', 'service');
}

export default {
  name: 'inject-service',
  initialize
};
```

**Comment by alexlafroscia** [comment]
Yes, this should technically be possible.  However, this is an anti-pattern.  The right approach is through service injection:

```js
import Ember from 'ember';

export default Ember.Route.extend({
  ajax: Ember.inject.service()
  
  model() {
    return this.get('ajax').request('my-endpoint');
  }
});
```

Is this just a question or an actual bug?

**Comment by rinoldsimon** [comment]
So wherever i use `ajax` request i should inject this`ajax: Ember.inject.service()` in each route ?

**Comment by alexlafroscia** [comment]
Yup, that's the nature of Ember services; you're explicit about injecting them into the specific places you need them.  That's not an `ember-ajax` thing, that's just an Ember Service thing.

More docs here: https://guides.emberjs.com/v2.8.0/tutorial/service/

**Comment by webark** [comment]
@alexlafroscia i understand that you wouldn't want to inject ember ajax into EVERY controller component or route, but was wondering if you where saying my using an initializer for dependency injection at all was an anti pattern, and if so why?

**Comment by alexlafroscia** [comment]
It's just not really talked about anymore. The `application.inject` API predates the `inject.service` API, so I wouldn't steer people toward that at this point.  If you _really_ wanted to get `ember-ajax` into every route, for example, I would probably do:

```
// inside some initializer function
Ember.Route.reopen({
  ajax: Ember.inject.service()
});
```

**Comment by alexlafroscia** [comment]
I could be wrong, but I wouldn't recommend `application.inject` to someone new to Ember at this point over `inject.service`

**Comment by webark** [comment]
hmm.. ok. The reopen seems really weird. And ok cool. I could see that. I didn't know if there where performance implications or future removal of that api or something.

**Comment by alexlafroscia** [comment]
Maybe "antipattern" wasn't the right term. It's more that `application.inject` isn't the recommended way of using services, but like I said, there's no reason it doesn't work.

**Comment by webark** [comment]
ok cool. That makes sense. Thanks!
