### ISSUE TITLE
Handle header matching in a case-insensitive way

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-ajax#184]
There are a few places in the code where we check the headers against some value (mostly to check if the request was a JSON API one).  Whenever we do this, we should do so in a case-insensitive way.

**Comment by XaserAcheron** [comment]
Took a peek through the code and it seems pretty straightforward. I'll probably have a poke at this later today once I get some time to get the dev environment set up.

**Comment by XaserAcheron** [comment]
Welp. "Later Today" really means "Tomorrow," I'm afraid. Got started but I've got some errands to run...

From a comment on the old PR:  Is there a particular preference toward using regexes to do the match? Looks like `toLowerCase()` would suffice in all the cases I'm seeing, though I could swing either way.

**Comment by alexlafroscia** [comment]
No worries, I know how that goes.

However you want to do the matching is fine with me.
