### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by gitjeff05** [ember-cli/ember-ajax#19]
I searched for an answer to this, but I was wondering if you could clarify some things about this statement in the README.md:

> ic-ajax also wraps requests in Ember.run which is no longer necessary on Ember 1.13+.

Do you mean that you no longer have to wrap requests or callbacks? I see [in ic-ajax that they wrap the success callback in an Ember.run](https://github.com/instructure/ic-ajax/blob/master/lib/main.js#L105). Also, it looks like [ember-ajax library does the same thing](https://github.com/ember-cli/ember-ajax/blob/master/addon/make-promise.js#L17) if I am reading it right.

So why is this no longer necessary? Ember 1.13 docs still state that wrapping async callbacks with `Ember.run` is a good idea. I couldn't find anything in the Ember docs that stated this.

**Comment by taras** [comment]
@gitjeff05 the code that you're pointing to was there to allow an upgrade path from `ic-ajax`. It should and will be removed before 1.0. It should throw a deprecation warnings when used. If it doesn't - it's a bug.

Here is an explanation from @krisselden 

<img width="669" alt="screen shot 2015-11-05 at 5 00 24 pm" src="https://cloud.githubusercontent.com/assets/74687/10983125/e260d0de-83de-11e5-9c08-bb62d0cf2f28.png">

**Comment by gitjeff05** [comment]
> so Ember.run isn't something people every think about anymore.

I cannot wait for that day. However, now I am even more confused about the run loop, event loop and promises.

**Comment by alexlafroscia** [comment]
@taras @gitjeff05 is this still an issue that needs a documentation update to fix?  Or is everything settled at this point?

**Comment by taras** [comment]
We need to restore the [`Ember.run` wrapper](https://github.com/emberjs/data/blob/master/addon/adapters/rest.js#L857) because it allows us to use the [wait()](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/wait.js) helper and update documentation to mention that we're wrapping in Runloop.

**Comment by alexlafroscia** [comment]
Gotcha.  I'll try to take care of that then :)

**Comment by alexlafroscia** [comment]
@taras since we did this:

> We need to restore the Ember.run wrapper because it allows us to use the wait() helper and update documentation to mention that we're wrapping in Runloop.

in #40, is this issue okay to close?
