### ISSUE TITLE
Accessing error message from server

### ISSUE THREAD

**Issue by celicoo** [ember-cli/ember-ajax#192]
Is it possible to access the error message that is coming from my API??

**Comment by alexlafroscia** [comment]
Yeah -- can you provide some context on what you're expecting to happen, and what the actual error behavior is?

**Comment by Unnumbered** [comment]
@alexlafroscia 
I think @celicoo meant something like this
```
this.get('ajax').post('my/url').catch( function(error) {
  # how to get access to the API response from here?
});
```

@celicoo 
read this: https://github.com/ember-cli/ember-ajax#access-the-response-in-case-of-error

**Comment by alexlafroscia** [comment]
Thanks for that @Unnumbered 

I'm going to close this and assume that that was the information that's being looking for. If that doesn't answer the question, I'm happy to re-open this so we can figure this out.
