### ISSUE TITLE
Setting a different host with no namespace is ignored

### ISSUE THREAD

**Issue by pijey** [ember-cli/ember-ajax#193]
Hi !

I think there is a problem when injecting the ajax service in a controller for instance and using directily when setting up a different host without namespace.
Exemple : 
- host : "http://localhost:8080"
- namespace : ""

When I call `this.get("ajax").request("my-request")...` I expect the request to hit the host I configured ("http://localhost:8080"). But the request hits the url **http://localhost:4200**.

In [this service](https://github.com/ember-cli/ember-ajax/blob/master/addon/mixins/ajax-request.js#L467) the regex always matches (because namespace is empty) and thus the request is made on the url **http://localhost:4200**.

As a workaround, I had to change my rest api to add a namespace i.e. "http://localhost:8080/api" and set up the ajax service this way : 
- host : "http://localhost:8080"
- namespace : "api"

**Comment by jherdman** [comment]
Hi pijey. Would you be able to provide a reproduction app, or a failing test?

**Comment by alexlafroscia** [comment]
Man, this host/namespace code is so problematic.  One of the big reasons I want to refactor this and come up with a better approach for Ember AJAX 3.

I'll add a failing test case with this configuration and work from there to fix this.

**Comment by pijey** [comment]
Ok great ! Sorry, I don't have much time these days to provide a failing test

**Comment by alexlafroscia** [comment]
I can't reproduce (see linked commit above). I'm going to close this for now -- if you can re-open with a reproduction, I'm happy to fix it!
