### ISSUE TITLE
Update header when token refresh

### ISSUE THREAD

**Issue by absemetov** [ember-cli/ember-ajax#214]
My settings not work:
authorizers/application.js
````
headers: Ember.observer('session.data.authenticated.token', function() {
     let headers = {};
     this.get('session').authorize('authorizer:application', (headerName, headerValue) => {
          headers[headerName] = headerValue;
     });
````

**Comment by alexlafroscia** [comment]
There are a number of issues here:

1. The `headers` property should either be an object or a computed property. Setting it to an `observer` means that we can't actually get the values here. Generally, `Ember.observer` is not recommended; there is a nice blog post [here](https://dockyard.com/blog/2015/11/16/best-practices-functional-programming-and-the-observer-effect) that goes into why. What you want here is a [computed property](https://guides.emberjs.com/v2.10.0/object-model/computed-properties/).
2. If this _was_ a computed property, you'd need to return the `headers` object, which would make the code look like this:
    ```js
    headers: computed('session.data.authenticated.token', function() {
      let headers = {};
      this.get('session').authorize('authorizer:application', (headerName, headerValue) => {
        headers[headerName] = headerValue;
      });
      return headers;
    })
    ```
3. If your `authorize` method is asynchronous, then this code isn't going to work.  Right now, we don't support `headers` providing a `Promise` that resolves to an object, but we could pretty easily; in fact, it might even make sense to do so.  If that's something you'd like, please make a separate issue so we can track progress on it.
