### ISSUE TITLE
Make attribute of data be dynamic?

### ISSUE THREAD

**Issue by BMahabir** [ember-cli/ember-ajax#222]
Quick question.  Given the simple basic usage example :

```
export default Ember.Controller.extend({
  ajax: Ember.inject.service(),
  actions: {
    sendRequest() {
      return this.get('ajax').request('/posts', {
        method: 'POST',
        data: {
          foo: 'bar'
        }
      });
    }
  }
});
```

is there any way to make `foo` dynamic?  If not, then I will eventually have to create a crapload of ajax calls where only a single one could do if I was able to do this.

**Comment by alexlafroscia** [comment]
What do you mean by dynamic? Like, what are you trying to do?

My guess is that you want to be able to use a variable for the key in the object passed to `data`.  If that's the case, then something like this might do the trick for you:

```js
export default Ember.Controller.extend({
  ajax: Ember.inject.service(),
  actions: {
    sendRequest(key) {
      const data = {};
      data[key] = 'bar';

      return this.get('ajax').request('/posts', {
        method: 'POST',
        data
      });
    }
  }
});
```

**Comment by webark** [comment]
@BMahabir with babel and ES2015 you can do dynamic keys with brackets.

```javascript
let foo = "thing"
let object = {
  [foo]: "value"
}```

**Comment by BMahabir** [comment]
@webark Thank you, this is exactly what I was looking for.  @alexlafroscia In the future, how could I have written my question to be more clear?  Thanks

**Comment by webark** [comment]
@BMahabir they both serve the same purpose, and babel coverts the ES2015 to the other. I don't think you asked your question wrong, just happened upon one of the joys of OSS.. multiple answers!! 😊

**Comment by alexlafroscia** [comment]
@BMahabir great question -- I don't think you did anything wrong here. It was more a matter of me not being sure whether this was an Ember AJAX-specific question, or just a JS question in general. Either way, happy to help.
