### ISSUE TITLE
handleResponse() receives {type: 'GET'} when requests are made with {method:'POST'}

### ISSUE THREAD

**Issue by nelstrom** [ember-cli/ember-ajax#229]
If I make a basic request [as documented in this project's README](https://github.com/ember-cli/ember-ajax#basic-usage):

```javascript
this.get('ajax').request('/posts', { method: 'POST' });
```

I expect the `handleResponse()` method to be able to see that this is a `POST` request. When I inspect the `requestData`, I see `type: 'GET'`:

```javascript
handleResponse(status, headers, payload, requestData)
  console.log(requestData)
  // => {type: "GET", url: "/posts"}
})
```

By contrast, if I make the request using either of the following:

```javascript
this.get('ajax').request('/posts', { type: 'POST' });
this.get('ajax').post('/posts');
```

Then the `handleReponse()` method gets `type: 'POST'`:

```javascript
// => {type: "POST", url: "/posts"}
```

I'm confused! Is there any difference between `type` and `method`?  If so, it would be good to clarify in the documentation. If not, then this seems like a bug that should be fixed.

**Comment by nelstrom** [comment]
The relevant method seems to be: [`_makeRequest()`](https://github.com/ember-cli/ember-ajax/blob/df2f838bb75806be738fd7fa8b737588923ec174/addon/mixins/ajax-request.js#L263-L266)

**Comment by alexlafroscia** [comment]
Hmm, that's very strange. What happens if you make the request with `.post`?

**Comment by nelstrom** [comment]
@alexlafroscia `this.get('ajax').post('/posts');` works as it should.

**Comment by alexlafroscia** [comment]
Intersting. I see how we could improve the handling around `method` being passed as a param, so I'll put that together.

**Comment by alexlafroscia** [comment]
I'm releasing `2.5.4` right now with my fix for this.

**Comment by nelstrom** [comment]
@alexlafroscia thanks! 🥇
