### ISSUE TITLE
Include bug fixes in pre-v3.0 releases

### ISSUE THREAD

**Issue by gnapse** [ember-cli/ember-ajax#234]
I just realized that the latest release does not include the fix in #226 and #227, because the release is not cut out from master. What other branch is being used for generating pre-3.0 releases? Is it possible to selectively include in this branch some of these fixes? This is important so that fixes are present in pre-3.0 releases. Since v3.0 will have breaking changes, it is important to continue supporting previous versions with bug fixes.

**Comment by alexlafroscia** [comment]
Blegh, yeah you're right. Should definitely fix that up. Really hate having the current version setup we have, with `3.0.0` on master and the releases behind it... I'll fix this up tonight and hopefully we can just ship 3.0.0 soon and get back to a more normal flow.

**Comment by jboler** [comment]
I also need the fix from #226. Maybe a 2.5.5 release? I'm getting `TypeError: Can't add property url, object is not extensible`.

**Comment by alexlafroscia** [comment]
So sorry guys, I'll put that together right now.

**Comment by alexlafroscia** [comment]
Branch building on Travis, I'll release when I know the tests pass

https://travis-ci.org/ember-cli/ember-ajax/builds/201984339

**Comment by alexlafroscia** [comment]
Alright, done. Thanks for the patience.
