### ISSUE TITLE
Minor typo in READ.md

### ISSUE THREAD

**Issue by yomashExpel** [ember-cli/ember-ajax#237]
In the section: https://github.com/ember-cli/ember-ajax/blob/master/README.md#access-the-response-in-case-of-error

the code snipping is missing parens () around the destructure for the '.then'.  Also adding the payload object for the catch is helpful as it seems that contains the server response.

Patch:
[readme_fix_update.txt](https://github.com/ember-cli/ember-ajax/files/769116/readme_fix_update.txt)

**Comment by alexlafroscia** [comment]
Hey @yomashExpel, thanks for catching that!

In the future, if you can create a [Pull Request](https://help.github.com/articles/about-pull-requests/), it makes it much easier for maintainers than submitting a patch directly. I created a pull request for your path this time though, just to make it quicker to get the fix in.

I tried to add you as the author of the commit, but I couldn't find your email address anywhere online, so I set it to your Github username and my email address.

Thanks for the contribution!

**Comment by yomashExpel** [comment]
no problem!  I was not sure the preference for such a small fix, but will do PR in the future.  Email: yousuf.ashparie@expel.io

**Comment by alexlafroscia** [comment]
Too late now for the email, unfortunately 😦  I'll make sure to add your username to the credits in the changelog once this makes it into a release, though!
