### ISSUE TITLE
Error even though my server is returning status 200 ok

### ISSUE THREAD

**Issue by jaredgalanis** [ember-cli/ember-ajax#238]
In the following ember-ajax request I'm returning status 200 ok, but the promise is still catching an error. Am I missing something?
```
    exportData() {
      return this.get('ajax').request('/export_requisition_statistics_report', {
        dataType: 'xlsx',
        data: 'rowData=' + JSON.stringify(this.get('sortedRowData')) + '&columnData=' + JSON.stringify(this.get('columnData')) + '&footData=' + JSON.stringify(this.get('footData')),
        method: 'post'
      }).then((response) => {
        Ember.Logger.info('response');
        Ember.Logger.info(response);
        return response;
      }).catch(function(error){
        Ember.Logger.info('error');
        Ember.Logger.info(error);
        return error;
      });
    }
```

**Comment by XaserAcheron** [comment]
What's the error message?

**Comment by jaredgalanis** [comment]
This ```Ember.Logger.info('error');``` is logging my success message:

```Object {success: true, status: 200}```

Which doesn't make much sense to me.

**Comment by alexlafroscia** [comment]
What is the `error` in the `.catch` handler?

**Comment by jaredgalanis** [comment]
@alexlafroscia, I'm sorry I don't understand. Isn't that what ```Ember.Logger.info('error');``` is logging based on its placement in the catch handler above?

**Comment by alexlafroscia** [comment]
I mean, if you're getting to your `Ember.Logger.info('error')` line there, then we know that _some_ error is happening. @XaserAcheron and I are asking _what_ that error is, what are the contents of the `error` argument to the handler?

**Comment by jaredgalanis** [comment]
I'm not seeing an error in the console. When I log the error argument it just logs my success object. How would I get the error you're looking for?

**Comment by alexlafroscia** [comment]
Have you come across the `debugger` keyword before?  It allows you to place a "breakpoint" in your code, where the browser will pause and let you step inside your code.

If you update your method to look like this, instead:

```javascript
    exportData() {
      return this.get('ajax').request('/export_requisition_statistics_report', {
        dataType: 'xlsx',
        data: 'rowData=' + JSON.stringify(this.get('sortedRowData')) + '&columnData=' + JSON.stringify(this.get('columnData')) + '&footData=' + JSON.stringify(this.get('footData')),
        method: 'post'
      }).then((response) => {
        Ember.Logger.info('response');
        Ember.Logger.info(response);
        return response;
      }).catch(function(error){
        debugger

        Ember.Logger.info('error');
        Ember.Logger.info(error);
        return error;
      });
    }
```

and then run your code with the dev tools open, it'll pause on the line with the `debugger`.  Once you have that, you can interact with your code through the console; the variable `error` will be defined there.  Attach a screenshot of its value.

**Comment by jaredgalanis** [comment]
Sorry guys, I actually had never used the debugger before. Here it is:
![screen shot 2017-02-14 at 4 26 27 pm](https://cloud.githubusercontent.com/assets/6305935/22950076/629cf4cc-f2d2-11e6-8930-8526ed8891f4.png)

**Comment by jaredgalanis** [comment]
Actually maybe this is more helpful. I'm not sure why the result of the promise would be undefined since I'm returning the success object.
![screen shot 2017-02-14 at 4 28 10 pm](https://cloud.githubusercontent.com/assets/6305935/22950167/b54f285c-f2d2-11e6-8e61-92ea3ec44cf6.png)

**Comment by jaredgalanis** [comment]
Actually digging further down I can see it relates it may relate to trying to coerce the dataType to be xlsx. Getting rid of xlsx as a dataType resolves the issue. Thank you guys!!!
![screen shot 2017-02-14 at 4 36 01 pm](https://cloud.githubusercontent.com/assets/6305935/22950572/0ed11218-f2d4-11e6-825e-d3b767729380.png)

**Comment by alexlafroscia** [comment]
Cool, I'm glad you got to the bottom of your issue!
