### ISSUE TITLE
Version 2.5.6 not on npm

### ISSUE THREAD

**Issue by kevinansfield** [ember-cli/ember-ajax#249]
I can see version [2.5.6 was released](https://github.com/ember-cli/ember-ajax/releases/tag/v2.5.6) but the latest version on npm appears to be `2.5.5` - was the npm publish step skipped?

**Comment by alexlafroscia** [comment]
Huh, it should have uploaded to NPM when it pushed the tag to Github....

**Comment by alexlafroscia** [comment]
Thanks for catching this, fixed now.
