### ISSUE TITLE
Can you publish the 2.5.7 version?

### ISSUE THREAD

**Issue by ctjhoa** [ember-cli/ember-ajax#267]
Hi,

The `2.5.7` is the only 2.X version with this commit fc0a47e06bd653582691ca0beb66cc129976829d
Can you release it please.

**Comment by ctjhoa** [comment]
PS: The 2.5.7 should not embed breaking change like 1f4ca9d53d96927ed262a3c320ed232ab8795020

**Comment by alexlafroscia** [comment]
Yeah, 2.5.7 was a mistake that I committed accidentally. Notice there are no git tags for it nor is there an NPM release.  I would remove the commits from `master` if I could, but that would require rebasing master and that just doesn't seem like a good idea.

If there are features contained there that you need, please check out `3.0.0-beta.1`
