### ISSUE TITLE
Do not publish betas as latest to npm

### ISSUE THREAD

**Issue by bjornharrtell** [ember-cli/ember-ajax#269]
Seems like beta versions are published using the default latest tag with npm. This makes most tooling view them as the latest stable version, which I think is undesirable. See https://docs.npmjs.com/cli/dist-tag for more details about tags.

**Comment by alexlafroscia** [comment]
Hmm yeah, that's definitely wrong. I just used `ember-cli-release` to do the publish, sorry about that!

I'll try to fix that up right now, I really appreciate you pointing it out!

**Comment by alexlafroscia** [comment]
Should be fixed now. Thanks again for noticing the issue and letting me know.
