### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by newton3** [ember-cli/ember-ajax#271]
At many places I see import statement being specified as -
`import AjaxService from 'ember-ajax/services/ajax';`

this doesn't seem to work. What works for me is below -
`import AjaxService from 'ember-ajax';`

Is that an issue with documentation?

**Comment by alexlafroscia** [comment]
Totally depends on what you're trying to import. The AJAX _service_ is exported at `ember-ajax/services/ajax` but an AJAX helper _function_ is exported from `ember-ajax` (and also `ember-ajax/request` which is the same module).

If I can see how you're trying to consume the module that you're importing I can let you know if something is broken or not.

**Comment by alexlafroscia** [comment]
I'm going to close this because I'm pretty sure this isn't an issue. I'm happy to re-evaluate upon submitted feedback.
