### ISSUE TITLE
Release with Babel 6 Changes

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-ajax#278]
Would y'all mind shipping another beta that includes the recent update to ember-cli-babel@6?

I'm trying to ensure that ember-cli@2.13 ships with only one version of babel, and this addon is one of the few remaining ones with Babel 5.

**Comment by alexlafroscia** [comment]
Yup! No problem. I've been thinking about just going ahead and releasing `ember-ajax` 3 this weekend since the beta has been available; I can pull the babel changes and then do that.

**Comment by alexlafroscia** [comment]
I'm going to put a PR together to clean up all of the open Greenkeeper PRs, put that up to master, then cut `3.0.0` from there. Or should I do a new beta? What do you think @rwjblue?

**Comment by alexlafroscia** [comment]
I released `3.0.0` which should have `ember-cli-babel@6.0.0-beta.10` as the dev dependency.
