### ISSUE TITLE
Doesn't seem to trigger jQuery Ajax Hooks

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-ajax#28]
Hi Taras!

I'm using `ember-ajax` from inside a component (to post an email to a mailing list).

I'm trying to write integration tests for the component, using `wait()`.

[(The code for wait is here.)](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/wait.js)

I do something like

```
this.$('button').click();

return wait().then(() => {
  // assertions
  asset.ok(...something);
});
```

However when I call `debugger` inside the `wait` function (in the link above) the value of `requests` is an empty array.  I'd assume that means `jQuery(document).on('ajaxSend', incrementAjaxPendingRequests);` and `jQuery(document).on('ajaxComplete', decrementAjaxPendingRequests);` aren't being called.

Do you have any thoughts / experience here?

**Comment by taras** [comment]
Can you please put a breakpoint on `https://github.com/switchfly/ember-test-helpers/blob/b04cc9cff517d3df9f4fde96b8c1839ec10cc91d/lib/ember-test-helpers/test-module.js#L190` and see if it's being triggered?

Ember Ajax isn't doing anything special to jQuery Ajax that would change default behaviour. If that is setup, it should work.

**Comment by hhff** [comment]
Just debug'd that breakpoint - the hooks are being successfully setup - but when I debug [here](https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/wait.js#L5) the hook is never fired.

This is from a WIP addon - I'll push it up now so I can show an example

**Comment by taras** [comment]
Is the setup function called before your test starts or when `wait()` is called?

**Comment by alexlafroscia** [comment]
This should have been addressed with #40, right?

**Comment by taras** [comment]
Yes, @hhff can reopen this if it's still a problem ;)

**Comment by hhff** [comment]
Oh sweet - will test on the weekend :heart:
