### ISSUE TITLE
`ajax.request` swallows errors

### ISSUE THREAD

**Issue by kevlarr** [ember-cli/ember-ajax#296]
So I've been trying to make an AJAX request that was failing before the request was made. I was trying to `catch` it to inspect the error, but the error was `undefined` so that wasn't really helpful.

I started digging through `ember-ajax` source and found this:
https://github.com/ember-cli/ember-ajax/blob/86ab8d0646ec37e5310affa3649e193cc45e135f/addon/mixins/ajax-request.js#L216

When I added a breakpoint there...
```
['catch'](function (_ref2) {
    var response = _ref2.response;

    reject(response);
});
```
... `_ref2` was a `TypeError` object...

```
> _ref2
TypeError: Cannot read property '_calendar' of undefined
    ...
```
... meaning `_ref2.response` is `undefined`, so `reject(undefined)` passes no error message to my `catch`.

I was quickly able to fix the reason I was getting this error, but it would have been nice if the actual error message was propagated.

**Comment by taras** [comment]
> I was quickly able to fix the reason I was getting this error

What did you do to fix the problem?

> it would have been nice if the actual error message was propagated.

This is default promise handling behavior, but we could throw an error in development when ajax response comes back with undefined.

**Comment by kevlarr** [comment]
> What did you do to fix the problem?

The `data` object I was passing to the request contained momentjs objects that I hadn't formatted to strings. Totally my fault - changing them to strings made the request go through.

> This is default promise handling behavior...

Default promise handling behavior is supposed to _pass_ error messages along, isn't it? Doing `reject(undefined)` doesn't really seem to be ideal behavior.

> ... when ajax response comes back with undefined

There wasn't an ajax response; the error was JS-based and happened client-side, preventing the response from being made. But my `catch` could not see the reason for the error, because of the `reject(undefined)` issue.

I was wondering if something like...
```
.catch((response) => {
        if (response instanceof Error) {
          reject(response);
        }

        reject(response.response);
      });
```
... might be acceptable. This would allow `AjaxRequest.request` to pass error messages up to the `catch` that consumes it.

**Comment by taras** [comment]
Feel free to add a PR with a test for your scenario and it can dictate the implementation. I'll be happy to push this through.

**Comment by kevlarr** [comment]
I'll keep trying later. Short of using Moment like in my exact use case, it's proving difficult to force a JS error in the exact same place.

**Comment by alexlafroscia** [comment]
I'm definitely in favor of the proposed alternate `catch` definition here; rejecting the param to `catch` if it's an Error object seems like a good idea, as long as we had enough tests to make sure that changing that doesn't break any behavior.

**Comment by devinus** [comment]
This is also hitting me. It means I can't wrap my requests in e.g. ember-backoff to retry them.

**Comment by kevlarr** [comment]
@devinus I backed off of Ember for awhile so I didn't really have a chance to get a test case (that didn't involve using Moment) working.. How were you getting the same bug? I wonder if yours would be a cleaner one to replicate in a test.

**Comment by alexlafroscia** [comment]
I haven't been able to re-create this issue so I'm going to close it. Any instances where an error is generated during the request being sent surfaces the error correctly

**Comment by kevlarr** [comment]
When this was an issue for me (I don't use Ember anymore), it was not errors while sending the request - it was errors while serializing the data model _before_ sending the request. (Eg. having a model with a date field that had a `moment` assigned instead)

**Comment by alexlafroscia** [comment]
Right -- I guess I could import `moment` and create an object to serialize with it to mimic the exact problem you had.
