### ISSUE TITLE
Server API version

### ISSUE THREAD

**Issue by manoharank** [ember-cli/ember-ajax#30]
As of now, I am using the `host` option to configure the server API version.

```js
// app/services/ajax.js

import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

export default AjaxService.extend({
  host: '/api/v1'
});

```

Is that ok?

**Comment by manoharank** [comment]
If yes, we can add it in the documentation.

If no, can we add another option `api_version` similar to `host` option.

**Comment by taras** [comment]
This feature is called `namespace` in Ember Data adapter. If you submit a PR with that then I'll merge it in.
