### ISSUE TITLE
ember-ajax doesn't work in unit tests because pretender doesn't allow full urls.

### ISSUE THREAD

**Issue by adhamhf** [ember-cli/ember-ajax#303]
Hi,

I'm trying to unit test a service that uses ember-ajax.  I want to use pretender since this is a unit test.

Here's sample code:

```
        Ember.$.ajax({
            host: '',  // <- required in unit test because of pretender
            url: '/postIt',
            datatype: 'json',
            method: 'POST',
            data: error.stack,
        }).then((response) => {
            console.log(response);
        }).catch((error1) => {
            console.error(error1);
        })
```

If I don't set 'host' to be an empty string then the host is set to 'http://localhost:7357' when I run the test.  [By design Pretender](https://github.com/pretenderjs/pretender/issues/23) doesn't support the use of host and path, it only supports paths.

I'm trying to figure out how to set the host to be empty, just when I'm running my unit tests.  The above code would cause our app to break in actual use.  Suggestions?

**Comment by XaserAcheron** [comment]
The linked Pretender issue in turn links to [this PR](https://github.com/pretenderjs/pretender/pull/66), which looks like it adds host support. Is Pretender still reporting an error if you try using a host?

**Comment by adhamhf** [comment]
@XaserAcheron  works!  using http://localhost:7357/postIt resolved the issue.  thxs.
