### ISSUE TITLE
Could not find module `url` imported from `ember-ajax/utils/url-helpers

### ISSUE THREAD

**Issue by QuantumInformation** [ember-cli/ember-ajax#307]
I'm on version 2.4.1 and when running on a page after upgrading to the latest ember-cli I'm getting

`Could not find module `url` imported from `ember-ajax/utils/url-helpers`

any ideas?

I know its an older version, but this was to avoid a refactor due to data coming back in a payload object.

**Comment by oskarrough** [comment]
Hi, also ran into this after upgrading. The utilities have been marked private and moved here https://github.com/ember-cli/ember-ajax/tree/master/addon/-private/utils

**Comment by alexlafroscia** [comment]
@oskarrough what in the utils is necessary to import into the addon? If there's something in there that people need, I'm happy to move it into a different place in the repo, but anything within `-private` can be broken at any time.

**Comment by oskarrough** [comment]
@alexlafroscia this PR used it but ended up copying it into ember-wordpress instead, as I remember.

https://github.com/oskarrough/ember-wordpress/pull/37

Perhaps @danteata knows whether it would be nice to have these helpers public?

**Comment by alexlafroscia** [comment]
I'm going to go ahead and close this due to inactivity. Feel free to re-open if this is still something that needs attention.
