### ISSUE TITLE
Unclear Upgrade Path for ic-ajax/raw

### ISSUE THREAD

**Issue by jherdman** [ember-cli/ember-ajax#31]
I have a use case in my application wherein I inspect response codes during long polling:

```javascript
return raw(membershipUrl, { type: 'HEAD', headers: { 'If-Modified-Since': ifModifiedSince } })
  .then((result) => {
    let jqXHR = result.jqXHR;

    // NOTE: if we have already manually refreshed or changed the membership, a different check will
    // already be in progress and we need not make any changes regarding the result of this stale update
    if (this.get('intervalId') !== lastInterval) {
      return;
    }

    if (jqXHR.status === 204) {
      this._newContentAvailable();
    } else {
      this.set('checkInProgress');
    }
  });
```

The upgrade path for such usage is unclear to me, it sort of seems like `¯\_(ツ)_/¯`. In general, I don't feel like headers, and response codes should be totally scrubbed from the response. It'd be nice to opt in to a more advanced use case.

**Comment by taras** [comment]
@jherdman this is an interesting use case. Not very common in my experience, but very valid. I think the ajax service is particularly well suited for this kind of a scenario. 

Would you be interested in pairing on this use case and see what kind of solution we could come up with together?

**Comment by mhretab** [comment]
>In general, I don't feel like headers, and response codes should be totally scrubbed from the response. It'd be nice to opt in to a more advanced use case.

:+1:

**Comment by stefanpenner** [comment]
dont we just pass through the raw request and jqxhr https://github.com/ember-cli/ember-ajax/blob/master/addon/make-promise.js#L20-L22 ?

**Comment by devinus** [comment]
I'm also unclear on how to make an Ember-friendly AJAX request that DOESN'T go thru the service I use everywhere else in my app. Sometimes I just want `request()`...

**Comment by taras** [comment]
@devinus you can just make another service that doesn't have any of those configurations.

**Comment by devinus** [comment]
@taras I *could*, but doing a service for a `raw` ajax request seems like conflating what a service means. Why now un-deprecate a simple way to make an Ember-friendly request?

**Comment by taras** [comment]
@devinus ok, you could leave `ajax` untouched and modify the extended version or continue using `ic-ajax`. 

The goal of `ember-ajax` is to provide a consistent way of handing `ajax` requests. It has different APIs than `ic-ajax`, so it doesn't make sense to maintain two interfaces within one library.

**Comment by devinus** [comment]
The only way around is to either create a "raw" ajax "service" since modifying the extended version seems like it would change the service. Using another library like `ic-ajax` would inflate app sizes further, when they can likely share the same code to do the same thing or `ember-ajax` could abstract the actual request code into a re-usable function that the service itself uses?

**Comment by taras** [comment]
@devinus yeah, we could do that. That's a good idea. I would just maintain `raw` but it'd use `ember-ajax` mechanics.

**Comment by alexlafroscia** [comment]
@alexspeller whoops, tagged you by mistake. Sorry!
