### ISSUE TITLE
AjaxService is undefined

### ISSUE THREAD

**Issue by rizkysyazuli** [ember-cli/ember-ajax#311]
Hey guys, i'm a noob and i stumble into this error when trying to do my first AJAX request.

```
TypeError: Cannot read property 'extend' of undefined
```

Which is coming from the ajax service:
```js
// app/services/ajax.js
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

export default Ember.AjaxService.extend({
  host: 'http://api.website.id'
});
```

Which is used by the user auth service:
```js
// app/services/auth.js
import Ember from 'ember';

export default Ember.Service.extend({
  ajax: Ember.inject.service('ajax'),

  registerUser(loginMethod, email, password, facebookID, facebookAuth) {
    return this.get('ajax').request('/members/register', {
      method: 'POST',
      data: {
        loginMethod,
        email,
        password,
        facebookID,
        facebookAuth
      }
    });
  }
});
```

I'm not sure what i did wrong. I'm totally new to Ember btw.

**Comment by rizkysyazuli** [comment]
weird. i reinstall the package (`ember install ember-ajax`) and now it works. this is supposed to be built into Ember right?

**Comment by alexlafroscia** [comment]
> this is supposed to be built into Ember right?

It used to be a default addon, but maybe that changed? Either way, I'm glad that you were able to get it working!
