### ISSUE TITLE
Relative host appears twice in url when set in service

### ISSUE THREAD

**Issue by VincentBons** [ember-cli/ember-ajax#312]
In environment.js we have:

``` javascript
rootURL: '/relative-host/',
host: '/relative-host',
```

In our ajax service we have:
``` javascript
import AjaxService from 'ember-ajax/services/ajax';
import Config from 'ember-get-config';

export default AjaxService.extend({
  host: Config.host
});
```

And the url becomes: ```http://www.domain.com/relative-host/relative-host/api``` but it should be ```http://www.domain.com/relative-host/api```

This is the case since v3.0.0. It is not a problem in v2.5.6.

It is not a problem when using a url like ```http://www.domain.com/relative-host/```

**Comment by VincentBons** [comment]
Okay, after doing some research my self, I have found that it is because stripSlashes in ajax-request removes the leading slash. In v2.5.6 host was not put through stripSlashes, it is in v3.0.0. 

Is there a specific reason for this? Or is it possible to reverse this again?

**Comment by alexlafroscia** [comment]
> I wouldn't mind making a PR for this. But it would be my first ever out here and I'm not quite sure what the rules are.

That would be awesome! All of this host-manipulation code has been a whole lot more problematic than you'd think; sorry you've come across another bug here.

So, to get a PR together, here's what you'll do:

1. Fork the repository, to make your own copy of it
2. Set up a test case that demonstrates the error you're seeing. This addon is pretty well tested, so you should be able to find a similar test in there that you can copy the pattern of.  There are pretty extensive tests around the URL building; you'll want to add something near the end of [this `describe` block](https://github.com/ember-cli/ember-ajax/blob/e8270f9217518c6217148638025ba9c37ae65a03/tests/unit/mixins/ajax-request-test.js#L732) that recreates the issue you're seeing
3. Make your test pass (without breaking anything else)!

I'm happy to help out if you get stuck.

**Comment by wolodarsky** [comment]
Ran into this same issue.  Realized I should have been setting the `namespace` as @alexlafroscia suggested.  This bug could probably be closed.

**Comment by alexlafroscia** [comment]
I like closing bugs! Will do -- if this is still a problem, we can re-open.
