### ISSUE TITLE
host is not used when namespace is empty.

### ISSUE THREAD

**Issue by emilt27** [ember-cli/ember-ajax#317]
Take a look at this line:
https://github.com/ember-cli/ember-ajax/blob/e8270f9217518c6217148638025ba9c37ae65a03/addon/mixins/ajax-request.js#L486

If I set the namespace to empty string it will not use a defined host.

**Comment by Charizard** [comment]
Similarly when I have a namespace as `/admin`, and I set the URL to `/admin/xyz` (by mistake), then the host is skipped.

**Comment by alexlafroscia** [comment]
@Charizard I know you made a PR around this space recently -- is this no longer an issue?

**Comment by Charizard** [comment]
@alexlafroscia Not sure. I will have to check this. Will get to it by tomorrow.

**Comment by dgavey** [comment]
This appears to still be an issue with the latest 3.0 release.

**Comment by alexlafroscia** [comment]
Thanks for the confirmation @dgavey

**Comment by alexlafroscia** [comment]
This was closed with https://github.com/ember-cli/ember-ajax/pull/391
