### ISSUE TITLE
Docs: readme could mention jquery ajax api

### ISSUE THREAD

**Issue by nruth** [ember-cli/ember-ajax#33]
It'd be helpful to mention the base library at the top of the readme, as some users will come to this having never used ic-ajax, and possibly without realising (or forgetting) it's jQuery based. 

[ic-ajax](https://github.com/instructure/ic-ajax) makes it clear near the start of the readme that
> This lib simply wraps jQuery.ajax with two exceptions: … Other than that, use request exactly like $.ajax.

I just tripped over the 'data' parameter like this:

```js
this.get('ajax').post('/admin/login', {email: email, password: password})
```
fills in the http request's password instead of putting it into the form data.

What I needed was 

```js
this.get('ajax').post('/admin/login', { data: {email: email, password: password} })
```

It's in the readme examples, but doesn't say what it is, and I thought it was structured data rather than request configuration.

**Comment by alexlafroscia** [comment]
@nruth Would you mind checking out the changes I made in #34 and letting me know if that seems like enough to cover it?

**Comment by nruth** [comment]
Yep that looks great, thanks!
