### ISSUE TITLE
Destructuring of `Ember.testing` will not work.

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-ajax#332]
`Ember.testing` is a getter/setter in Ember, and destructuring like this will only read its value at the time the module is evaluated. In this case, `Ember.testing` will most likely be `false` when the module is evaluated, then change to `true` _during_ the test. This behavior somewhat recently changed in https://github.com/emberjs/ember-test-helpers/pull/227 (which is included in `ember-cli-qunit@4.1.0` / `ember-qunit@3.0.0`).

https://github.com/ember-cli/ember-ajax/blob/3314904e1f2c52f1663bc8ed6d39b341edf54034/addon/mixins/ajax-request.js#L39

https://github.com/ember-cli/ember-ajax/blob/3314904e1f2c52f1663bc8ed6d39b341edf54034/addon/mixins/ajax-request.js#L91-L95

**Comment by alexlafroscia** [comment]
I see, so we should always use `Ember.testing`. I can definitely update that.

Is there a new API being introduced for the new `@ember/__MODULE__` syntax?

**Comment by rwjblue** [comment]
Yes, there will be a non-globals API, but we just need to decide the actual module path and pull the trigger.
