### ISSUE TITLE
how to set timeout on ember-ajax calls

### ISSUE THREAD

**Issue by leofoto** [ember-cli/ember-ajax#339]
Hi there
whenever i am making an ember-ajax call to any endpoint, can i set a timeout feature (which basically throws an error, when I don't get the response in x milliseconds) and calls an error call back for me (where i can decide what to do)..

The current timeoutError is only happening when the API that I called returned with a TimeoutError right ?

**Comment by alexlafroscia** [comment]
Correct; a `TimeoutError` corresponds to an actual HTTP timeout.

You can access the underlying `XHR` on the response from any of the `ember-ajax` methods, so you can definitely do something like this (totally pseudocode off the top of my head, here, so don't mind any errors)

```javascript

function getWithTimeout(url) {
  const response = this.get('ajax').get(url);
  
  const timer = window.setTimeout(function() {
    response.xhr.abort();
  }, TIMEOUT_AMOUNT);

  return response.then(result => {
    window.clearTimeout(timer);

    return result;
  });
}
```
