### ISSUE TITLE
Cross domain call succeeds but error dumped to console

### ISSUE THREAD

**Issue by ksnyde** [ember-cli/ember-ajax#345]
I have **download** endpoint which is properly setup for CORS, in my own service I call this endpoint like so:

```js
  download(request) {
    request = Object.assign(request, { userId: this.get('current.user.id') });
    console.log('request: ', request);

    return this.get('ajax').post(
      'https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/transporter/download',
      {
        data: request
      }
    );
```

The request goes out without error and looking at the network panel you can see from its perspective all is good:

![image](https://user-images.githubusercontent.com/980757/37680846-54bc7120-2c42-11e8-8f77-2970c677de8e.png)

And yet Ajax request fails with the following errors:

![image](https://user-images.githubusercontent.com/980757/37680930-8873c2fc-2c42-11e8-8dfe-2380eb0d8828.png)

What kind of dark magic is this? I guess I could catch the error and ignore it but it feels like a problem worth reporting (or possibly a misunderstanding on my part).

**Comment by ksnyde** [comment]
Having now caught the error, I can see that it's reporting that: "The ajax operation was aborted". Does this make sense? The network request DOES connect and return successfully.

**Comment by alexlafroscia** [comment]
Hmm, so it looks `ember-ajax` considers it an `AbortError`, likely because the status code on the jQuery object is `0`. It seems that jQuery uses `0` for CORS issues.

It looks and sounds like a CORS issue, so I would guess that it is one. I don't understand your reasoning that it isn't a CORS issue, since the response from the server seems to lack the `Access-Control-Allow-Origin` headers that would be expected.

**Comment by alexlafroscia** [comment]
I'm sure you've also looked online and come across this StackOverflow errors, but have you tried setting `crossDomain: true` in the jQuery options?

https://stackoverflow.com/a/25924543/2250435

**Comment by alexlafroscia** [comment]
I'm going to close this for now because it doesn't seem to actually be an `ember-ajax` bug but instead a CORS issue. If there's something I can be doing differently in `ember-ajax` please let me know and we can take it from there.
