### ISSUE TITLE
Interest in TypeScript?

### ISSUE THREAD

**Issue by Bouke** [ember-cli/ember-ajax#346]
Hello! I use your addon and really appreciate it. I'm also participating in [this quest issue to add TypeScript support throughout the Ember.js ecosystem](https://github.com/typed-ember/ember-typings/issues/14). (This will benefit to anyone who uses your addon, not just TypeScript users!) Are you interested in either converting the addon to use TypeScript itself, or in adding type definitions? I already have worked out most of the type definitions in my own project, which I could provide through [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead. Thanks!

**Comment by alexlafroscia** [comment]
Hmm, yeah, that would be interesting.

I know almost nothing about TypeScript though, or the pitfalls of converting an Ember addon.

Which would you suggest? Providing a type definition or just converting the addon over?

**Comment by Bouke** [comment]
The easiest starting point would be to add the type definitions. Converting the addon over requires a substantial amount of time, whereas the quickest gains (for users) would be provided with the typings already. If you're interested I can have a go at a PR for adding those typings to this repo?

**Comment by alexlafroscia** [comment]
Sure thing. Would TypeScript users just "magically" get type information with the definition being part of the repo?

Also, is there a process around ensuring the types are up-to-date? My concern with external type definitions is only that it becomes something to remember whenever the API changes.

OTOH this is really not much an issue since this addon will likely never see a major API change; I pretty actively encourage people to avoid this addon and use `ember-fetch` instead.

**Comment by chriskrycho** [comment]
👋 TS users *will* just get type info with the definition living in the repository. Even better, having them ship with the addon means that JS users will get code completion and any documentation attached to the type definitions if their editor supports it (and everything from Vim to IntelliJ idea does!). The ember-cli-typescript team will be happy to help check the type definitions and make sur ethey’re right!

**Comment by alexlafroscia** [comment]
Sweet. Let's do this, then! Let me know if there's anything on my end that can be done to improve the TypeScript experience.

**Comment by alexlafroscia** [comment]
I've been converting a bunch of my addons to TypeScript lately and enjoying it, so I'm actually looking into just converting the addon entirely instead of just adding a type definition.

**Comment by alexlafroscia** [comment]
@bcardarella @chriskrycho What is the standard around your application depending on third-party types?

`ember-ajax` has some type definitions that depend on `@types/node` and `@types/jquery`. Should those be listed under `dependencies`? `devDependencies`? Or is there some other way to do it?

**Comment by chriskrycho** [comment]
They should normally be devDependencies.

**Comment by alexlafroscia** [comment]
👍 Excellent. Have been making some good progress on this and learning a lot about TypeScript in the process!

**Comment by alexlafroscia** [comment]
@Bouke Can you share the type definition that you created with me? It might be helpful in a few places that I'm struggling right now.

**Comment by alexlafroscia** [comment]
Just for information about the progress here, I've been working on the TypeScript conversion and #355 at the same time. I want to make sure that the FastBoot test is in place first, since I need to ensure that moving to TypeScript doesn't break anything and we have never had any real test coverage around the FastBoot support.

**Comment by alexlafroscia** [comment]
Discovered an RSVP typings bug in the process 🙃 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26640

**Comment by alexlafroscia** [comment]
Rather than continuing here, maybe I can ask some questions in #356 to get clarification on the "right way" to do certain things.

An updated version of the `promise.ts` class can bee sound on the PR linked above.
