### ISSUE TITLE
Remove `ic-ajax` compatibility code

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-ajax#35]
For Ember Ajax 1.0 we should remove already deprecated `ic-ajax` code.

**Comment by stefanpenner** [comment]
will this then be part of CLI 2.x ? or..

**Comment by taras** [comment]
@stefanpenner It already is https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/package.json#L23

**Comment by stefanpenner** [comment]
i mean, it must be released before ember-cli releases a stable 2.0 Or it would be a potential breaking change.
