### ISSUE TITLE
Add missing Ajax failures

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-ajax#36]
For example, 400 should throw BadRequest error.

**Comment by alexlafroscia** [comment]
Other than `BadRequest`, what errors would you want to throw?

**Comment by taras** [comment]
I'm thinking `BadRequest` 400 and `Server Error` 5xx without distinguishing for different kinds of server Errors.

**Comment by alexlafroscia** [comment]
Alright, sounds good.
