### ISSUE TITLE
Typo in release notes for v3.0.0

### ISSUE THREAD

**Issue by danwenzel** [ember-cli/ember-ajax#371]
In [the release notes for v3.0.0](https://github.com/ember-cli/ember-ajax/releases/tag/v3.0.0), when explaining how to extend the ajax service and pull in `LegacyNormalizeErrorResponse`, there is a typo in the code.  It should use `extend`, not `extends`:

#### Current

```js
export default AjaxService.extends(LegacyNormalizeErrorResponse, {
  // Your other configuration here
});
```

#### Proposed

```js
export default AjaxService.extend(LegacyNormalizeErrorResponse, {
  // Your other configuration here
});
```

**Comment by alexlafroscia** [comment]
Thanks for catching that! I just fixed it.

**Comment by danwenzel** [comment]
🎉  Thanks!
