### ISSUE TITLE
Generated types are somehow broken

### ISSUE THREAD

**Issue by makepanic** [ember-cli/ember-ajax#388]
Hi,
this addon provides typescript types in `mixins/**/*.d.ts`.

Somehow these are kinda broken.

* there are references added which point to a local user 
(`/// <reference path="../../../../../../../../../Users/alafroscia/Code/ember/ember-ajax/node_modules/@types/ember/index.d.ts" />`):

![20181001-111038](https://user-images.githubusercontent.com/1205444/46281010-c01c7e00-c56d-11e8-9fbc-1d45471316ef.png)

* it uses ember api in a weird way (`'ember'.Ember.ComputedProperty`)
  * i'm unsure if this maybe somehow works but I've never seen this used and TypeScript complains:

![20181001-111020](https://user-images.githubusercontent.com/1205444/46281136-18538000-c56e-11e8-8032-f3f9dc54247e.png)

This results in a consuming addon not being able to precompile types:

![20181001-111002](https://user-images.githubusercontent.com/1205444/46281431-ee4e8d80-c56e-11e8-8de1-ec1ef414ad9a.png)

**Comment by alexlafroscia** [comment]
Huh! Sorry about that, I'm not really sure what's up there since all of those `.d.ts` files are auto-generated by tools. I can definitely try to update the tools and generate them again, and will check out what it produces to see if it still includes those strange paths.

**Comment by makepanic** [comment]
No worries. I'll see if i can help in any way.

You're only using the default ember-cli-typescript `ember ts:precompile` right?

**Comment by makepanic** [comment]
I've looked into upgrading dependencies to get latest typescript to work. 
There are some DefinitelyTyped issues i'll have to fix to get this ready to publish.

Once that worked with some modified types, everything looks to be working fine:

![20181001-201041](https://user-images.githubusercontent.com/1205444/46309470-ba01be00-c5bc-11e8-89d4-216b0c0e7af1.png)

**Comment by alexlafroscia** [comment]
> You're only using the default ember-cli-typescript `ember ts:precompile` right?

Yup, nothing weird here

> There are some DefinitelyTyped issues i'll have to fix to get this ready to publish.

I run into issues around the `@types` _all the time_. I always need to pin a specific `resolutions` version for each of them, otherwise all hell breaks loose.
