### ISSUE TITLE
ember-ajax does not work with Ember 3.8 when transpiling to ES5

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-ajax#431]
[Original issue in Ember.js](https://github.com/emberjs/ember.js/issues/17643).

[Babel cannot transpile to ES5 extending from some built-in types](https://babeljs.io/docs/en/caveats/#classes) which means that [extending EmberError](https://github.com/ember-cli/ember-ajax/blob/3ed08ceb0b797a8022477edc8274e8db22c35c4b/addon/errors.ts#L3-L13) won't work any more in ES5 since Ember 3.8 because it is the [same as Error](https://github.com/emberjs/ember.js/pull/17216).

**Comment by Turbo87** [comment]
as mentioned on Discord, the way I would propose to fix this is:

1) update ember-cli-babel to v7 and check if that fixes the test suite
2) update the Node.js compatibility claims in `package.json` and PR it
3) open a PR for 1) which also updates the "Compatibility" section, adding CLI 2.13+ requirement
4) get it released as v5.0.0
5) update the app blueprint in Ember CLI
6) get that released as v3.8.1
