### ISSUE TITLE
deprecation warning ember 3.9 - computed-property.volatile

### ISSUE THREAD

**Issue by fran-worley** [ember-cli/ember-ajax#446]
When running in ember 3.9 we get the following deprecation warning. Is this something that you plan on fixing or is the idea that we move to ember-fetch?

> Setting a computed property as volatile has been deprecated. Instead, consider using a native getter with native class syntax. [deprecation id: computed-property.volatile]

**Comment by boris-petrov** [comment]
@fran-worley - where do you get this warning from? [Searching for volatile in ember-ajax](https://github.com/ember-cli/ember-ajax/search?q=volatile&unscoped_q=volatile) doesn't yield any results for code that uses `volatile`.

**Comment by fran-worley** [comment]
@boris-petrov I was probably reading the `volatile` comment... As you say, no use of volatile in this addon so I'll close - Sorry for bothering you! I find ember deprecations so hard to debug when they come from node_modules!

**Comment by boris-petrov** [comment]
@fran-worley - no worries! Yes, deprecations could be a pain. Hope you figure them out soon!
