### ISSUE TITLE
Always including headers could lead to unintentional leaking of token credentials

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-ajax#45]
Per https://github.com/ember-cli/ember-ajax#custom-request-headers, if headers are defined they are send on all requests made with `ember-ajax`. The suggested use case here is to send headers including token authentication. 

This seems risky. If anywhere in the application uses `ember-ajax` to make a request to a third-party, these credentials could be leaked. 

Chatted with @taras, he suggested that as a solution headers could only be included by default when using the 'host' option or a relative URL.

**Comment by taras** [comment]
Thank you for reporting this
