### ISSUE TITLE
Any plans to switch to fetch?

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-ajax#450]
👋

I was curious if there were any plans in the works to convert this addon to use fetch? I love the API here, but would like to remove jQuery from our app. If this intends to stay a wrapper for jQuery ajax, I am thinking I will release another addon, with a compatible API, that uses fetch instead.

**Comment by hefox** [comment]
If not, it'd be good to update documentation to how to use this with current ember, which is to add jquery plugin as far as I can tell:

```
ember install @ember/jquery
ember install @ember/optional-features
ember feature:enable jquery-integration
```

(Via the deprecation guide for 3.x)

**Comment by rwwagner90** [comment]
I've been working on a drop in replacement for ember-ajax that uses fetch. We're not ready to announce it quite yet, but it should be ready soon!

**Comment by adambedford** [comment]
@rwwagner90 Any update on your drop-in replacement? Would love to get away from using `fetch` directly in our new non-jQuery app...

**Comment by rwwagner90** [comment]
@adambedford it's more or less complete, but not published on npm yet. I'll see if we can get it officially published to npm over the next couple days.

**Comment by rwwagner90** [comment]
@adambedford we just published ember-ajax-fetch. Give it a try! https://github.com/expel-io/ember-ajax-fetch

**Comment by adambedford** [comment]
@rwwagner90 Digging into the new library after a few days away and it's really awesome. Thanks so much for the work. Great to have this!

**Comment by rwwagner90** [comment]
@adambedford you're welcome! Please let us know if you encounter any issues.
