### ISSUE TITLE
[5.1.0] Type-definitions are missing from release

### ISSUE THREAD

**Issue by boris-petrov** [ember-cli/ember-ajax#460]
@Turbo87 - thanks for releasing a new version! However, in it, `.d.ts` files are missing.

**Comment by boris-petrov** [comment]
Actually the whole release seems broken: `Could not find module `ember-ajax/errors``.

**Comment by Turbo87** [comment]
ugh... typescript... 🙄

**Comment by Turbo87** [comment]
looks like it did not precompile anything when I ran `npm pack`. should be fixed now with v5.1.1
