### ISSUE TITLE
Your handler code inside .then or .catch will automatically be wrapped in an Ember run loop for maximum compatibility with Ember, right out of the box.

### ISSUE THREAD

**Issue by rtm** [ember-cli/ember-ajax#47]
I'm confused about what this means. Do the promises returned by ember-ajax have their own customized then method? If that's the case, that seems like a bad idea, since one common pattern with promises is to do

```
promise . then(functionReturningAPromise)
```

And in such a case, the returned promise is supposed to "subsume" or "substitute" for the promise returned from the function. If in fact `then` handlers are buried in ember run calls, it would seem like it could not work as it should. Instead, we end up with a promise whose value is a promise, which is semi-useless, which is what seems to be happening to me. 

I have the following case of chaining API calls, the first which gets a token and the second which makes the "real" call, so I'm trying to do something like this:

```
postData(token, data) { return this.get('ajax').post(url, {data}); },
go() { 
  return this.getToken() . 
    then(response => this.postData(response, data)) . 
    then(response => console.log(response));
}
```

Unless I'm missing something, this is not working because the `response => this.postData(response, data)` action, which evaluates to a promise, which the promise chain should be adopting as its value, is perhaps instead getting put inside an Ember. run, with the promise being resolved to a promise? Then again, maybe I'm just having a major hallucination.

**Comment by taras** [comment]
Hi @rtm, I'll do my best to clarify this. 

There is a promise that's created when the request is made. This promise has `resolve` and `reject` callbacks that need to be called to resolve or reject the promise. We pass these callbacks to `Ember.run` to make sure that there is an Ember Run Loop running when the promise chain is executed. You can see that here https://github.com/ember-cli/ember-ajax/blob/master/addon/ajax-request.js#L61

This entire process should be completely transparent to you. If it's not, then it's a bug. 

> Unless I'm missing something, this is not working because the response => this.postData(response, data) action, which evaluates to a promise, which the promise chain should be adopting as its value, is perhaps instead getting put inside an Ember. run, which the promise being resolve to a promise?

This shouldn't be happening (if it is). Are you able to create a failing test to show this?

**Comment by rtm** [comment]
@taras Thanks for clarifying. I'll close this now.
