### ISSUE TITLE
Doesn't play nice with `wait()` in Integration tests

### ISSUE THREAD

**Issue by hhff** [ember-cli/ember-ajax#48]
Just updated to `v2.0.0-beta.1` in an addon project to test whether #28 was fixed - unfortunately the problem persists.

As mentioned there, Testing code (component integration test) like this...
```
// Trigger something that uses `ember-ajax` under the hood
this.$('button').click();

return wait().then(() => {
  // assertions
  asset.ok(...something);
});
```

...won't actually wait for the Ember Ajax request to return.

Will do a bit of investigating now - but just wanted to reopen this.  Thank you~ :heart:

**Comment by hhff** [comment]
Scratch that, works great!  My bad

**Comment by rwjblue** [comment]
Whew! OK, great to hear.  I was worried for a minute...

**Comment by hhff** [comment]
Haha yeah was just about to put on the deepdive helmet

**Comment by hhff** [comment]
Ahhh dang - I'm sorry to blow this repo up - I doubled tripped - I am actually still experiencing this problem.

I just pushed up a repo (it's a simple email form for Mailchimp) to reproduce this issue.

[Here](https://github.com/hhff/ember-chimp/blob/master/tests/unit/components/ember-chimp-integration-test.js#L47) is the line in the testing code that isn't waiting for for 
Ajax Request.

[Here's](https://github.com/hhff/ember-chimp/blob/master/addon/components/ember-chimp.js#L77) the line where the Ajax Request is actually sent.

Hopefully will get a chance to look into this today

**Comment by taras** [comment]
@hhff It should work. Can we pair on this to try to figure this out? I'd like to find out why it's not working.

**Comment by hhff** [comment]
@taras yeah totally!  will ping u on ember slack

**Comment by taras** [comment]
Alex and I paired on this issue and it turns out that you're using JSONP which doesn't trigger `ajaxSend` and `ajaxComplete` events. We're going to manually trigger these events when JSONP is used. We have a working solution. Alex is going to prepare a PR.

**Comment by alexlafroscia** [comment]
Hey @hhff I updated `ember-chimp` to the latest version of the Ember CLI as part of the debugging earlier today.  Would you want that PR'd to you? Or should I just trash it?

**Comment by hhff** [comment]
@taras ahhhhhhh bingo

@alexlafroscia a PR would be amazing!!

awesome work guys :+1:
