### ISSUE TITLE
Content-type and Encoding

### ISSUE THREAD

**Issue by brandonparsons** [ember-cli/ember-ajax#49]
Hi there,

I'm trying to send a custom ajax call to my backend server, which is a JSONAPI.org server. I don't know why, but when I try to send a `Content-Type` header (`application/vnd.api+json`) `ember-ajax` is form encoding the request.

```javascript

      this.get('ajax').request('/api/v1/things', {
        method: 'POST',
        data: {
          // ......
        },
        headers: {
          'Content-Type': 'application/vnd.api+json',
          'Accept': 'application/vnd.api+json'
        }
      }).then( jsonapiResponse => {
         // .....
      });
```

Checking my server logs is getting the body sent as a big form encoded blob, rather than JSON.

Am I doing something wrong?

**Comment by alexlafroscia** [comment]
No, it looks like you're using it right... Are you using the AJAX service that comes with the addon? Or have you extended it?

**Comment by brandonparsons** [comment]
Hi @alexlafroscia - I did extend it, but only barely:

```javascript
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';


export default AjaxService.extend({

  session: Ember.inject.service(),

  headers: Ember.computed('session.data.authenticated.token', {
    get() {
      let headers = {};
      const authToken = this.get('session.data.authenticated.token');
      if (authToken) {
        headers['Authorization'] = `Bearer ${authToken}`;
      }
      return headers;
    }
  })

});
```

**Comment by rwjblue** [comment]
I could be misreading something, but I don't see where options.headers and the CP headers are merged (looked here: https://github.com/ember-cli/ember-ajax/blob/master/addon/ajax-request.js#L148)

Have I just overlooked it?

**Comment by brandonparsons** [comment]
@rwjblue Does this mean that I should only be setting headers in one place? So instead of extending the `ajax` session just put the auth header on every request that I am not making through `ember-data`?

**Comment by brandonparsons** [comment]
Doesn't seem to matter too much. Pulled setting the auth headers into all calling locations, e.g.:

```javascript
this.get('ajax').request('/api/v1/things', {
  method: 'POST',
  data: {/* ... */},
  // contentType: 'application/json',
  headers: {
    'Authorization': `Bearer ${this.session.get('token')}`,
    'Content-Type': 'application/vnd.api+json',
    'Accept': 'application/vnd.api+json'
  }
}).then( jsonapiResponse => {
  /* ... */
});
```

Can confirm that both the `Authorization` and the `Content-Type` headers are being sent, however my data is still being sent as form-encoded. :(

Same story with/without `dataType: 'json'`

**Comment by alexlafroscia** [comment]
So, I checked out the code again and realized that I was wrong before; that is _not_ the correct API for adding headers.  Currently, there is no way to add headers on a per-request basis, and the same is true for `$.ajax` which also doesn't support a `headers` property.  Instead, the correct way to add those headers in `$.ajax` land is [like this](http://stackoverflow.com/a/13515414/2250435).

@taras: do we want to support providing that configuration on a per-request basis? My gut says that don't want to expose any more per-request API that we absolutely need to.  What would be the right way to handle this situation? Making a second AJAX service?

**Comment by alexlafroscia** [comment]
Okay, so I wrote up some test cases and realize that the behavior right now is a little confusing for sure.  If your request provides a `headers` config property, they _do_ get applied, but if the same key is defined by the class's `headers` property, then that one overrides the per-request value.  While unexpected, this is due to the fact that, apparently, a header set using `xhr.setRequestHeaders` has higher precedence than a key on the `headers` hash.

I also noticed that whatever is specified in the `contentType` will be overwritten by a `Content-Type` header specified in the class.

However, is seems like neither of these are the case that @brandonparsons has noticed, where there's only the `Content-Type` header present in the one place.  That behavior _is_ covered in our tests, and should be working fine.

**Comment by brandonparsons** [comment]
@alexlafroscia  For sure the right content-type is being sent in the case I was showing. I can't for the life of me figure out how to get the body to be json encoded though :)

**Comment by alexlafroscia** [comment]
@brandonparsons I'm sorry, maybe I completely mis-understood the problem here; I thought the `Content-Type` header was the issue.

**Comment by taras** [comment]
@brandonparsons Content-Type should be specified as they're in jQuery by providing `contentType` key to options hash. 

```javascript
this.get('ajax').request('/foo', { contentType: 'application/vnd.api+json' })
```

For all other headers, you can use `headers` hash as you have been.

**Comment by brandonparsons** [comment]
@alexlafroscia @taras Hi guys, thanks for your help.  The `Content-Type` header is being correctly applied (I'm watching the server logs to confirm).  This can be accomplished either by explicitly setting the `Content-Type` property on the `headers` hash, or by using the jQuery style `contentType` key as @taras mentioned.

The problem I'm having is that it would appear that `ember-ajax` (or maybe jQuery?) doesn't know how to handle `application/vnd.api+json` and isn't JSON encoding the request body. It's form encoding it.

Does this make sense?

**Comment by taras** [comment]
Yes, this makes sense. We should make ember-Ajax aware of jsonapi content type
