### ISSUE TITLE
Overwrite error method?

### ISSUE THREAD

**Issue by caselas** [ember-cli/ember-ajax#57]
I see an example for "globally" handling errors when the status is 200, but what about other status codes like 401 or 403?

I would think something like this would be possible:

```javascript
// app/services/ajax.js

import AjaxService from 'ember-ajax/services/ajax';

export default AjaxService.extend({
  isUnauthorized(status, headers, payload ) {
    // some custom logic
  }
});
```

Rather than handling specific errors on each request, is it possible to handle them globally?

**Comment by alexlafroscia** [comment]
Do you mean for detecting the errors? Or specifying a handler function on a per-error-type (`401`, `403`, etc) basis?

**Comment by alexlafroscia** [comment]
Right now, the way to do that would probably be overwriting the 

```javascript
import AjaxService from 'ember-ajax/services/ajax';
import { isUnauthorized } from 'ember-ajax/errors';

export default AjaxService.extend({
  handleResponse() {
    const result = this._super(...arguments);
    if (isUnauthorizedError(result)) {
      // Do whatever you need to do
    } else {
      return result;
    }
  }
})
```

**Comment by caselas** [comment]
The former is exactly what I was looking for, just didn't realize I had to import the error. (Still getting the hang of es6.)

Thanks @alexlafroscia

**Comment by alexlafroscia** [comment]
No problem! You could also do a simple type check of the `result` variable, like:

```js
if (result instanceof UnauthorizedError) {
  // ...
}
```

But then you need to import `UnauthorizedError` instead.  We provide the helper methods for doing this exact kind of thing -- I'm glad that works for you!

**Comment by taras** [comment]
I think we should make helpers the recommended way to tests errors because
it will allow us to also check for Ember Data errors.

-- 
Taras Mankovski

**Comment by alexlafroscia** [comment]
Yeah, for sure. I was more just pointing out that the `UnauthorizedError` is a unique type that can be checked that way, too

**Comment by urbany** [comment]
Hi @alexlafroscia this handleResponse method is very interesting, it would be great if you could add it to the README, this exact example is very helpful.

**Comment by alexlafroscia** [comment]
@urbany Thanks! @taras and I are planning to put together a little documentation site with examples and stuff of these kinds of things, since I want to avoid saturating the README with too much information.  I'll make sure that that example ends up in there!
