### ISSUE TITLE
Custom endpoint path ignored 

### ISSUE THREAD

**Issue by Padchi** [ember-cli/ember-ajax#68]
```javascript
import Ember from 'ember';
import AjaxService from 'ember-ajax/services/ajax';

export default AjaxService.extend({
  namespace: '/api/v1',
  host: 'http://api.example.com'
});
```

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  ajax: Ember.inject.service(),
  model() {
    return this.get('ajax').request('/posts');
  }
});
```

Results in: `GET http://api.example.com/posts` without namespace.

**Comment by taras** [comment]
@Padchi are you using the beta? could you please create a failing tests?

**Comment by Padchi** [comment]
@taras I'm using 0.7.1 with ember/ember-cli 2.4.1. Sorry I can't, havn't created a single test in my life. Im all in for trial and error in the browser.

**Comment by alexlafroscia** [comment]
Namespace support only landed in `0.2.0-beta.2`.  Please update to the latest beta and let us know if that takes care of it.

**Comment by taras** [comment]
@Padchi here is an intro to testing with Ember https://vimeo.com/146960505 (just in case you'd like to learn :) )

**Comment by Padchi** [comment]
@alexlafroscia my bad, `namespace` works in `2.0.0-beta.2`. Haha thanks @taras ;)
