### ISSUE TITLE
.request() 'method ' option is not working, only send GET request

### ISSUE THREAD

**Issue by JennieJi** [ember-cli/ember-ajax#69]

**Comment by alexlafroscia** [comment]
I couldn't reproduce this, and added a test that verifies that it works correctly.  If you're still having this issue and can show me a situation where it's reproducible, I'm happy to re-open the issue to fix this.

**Comment by JennieJi** [comment]
@alexlafroscia I am sure that 'method' is not working, and later on I found the truly working option is 'type'. So I suspect your example in README.md is wrong:

`
import Ember from 'ember';

export default Ember.Controller.extend({
  ajax: Ember.inject.service(),
  actions: {
    sendRequest() {
      return this.get('ajax').request('/posts', {
        method: 'POST',            // This don't work, change to "type: 'POST'" then it works...
        data: {
          foo: 'bar'
        }
      });
    }
  }
});
`

**Comment by alexlafroscia** [comment]
Did you see the test case that I added to the repo in the commit reference above? It verifies that adding the `method` option does change the request type. 

According to the jQuery API documentation, the `type` and `method` keys are interchangeable. 

If you can post a demo app with the broken behavior, or submit a PR with a failing test, that would be a huge help toward tracking this down!
