### ISSUE TITLE
Problematic deletion of trailing slashes in urls

### ISSUE THREAD

**Issue by fpauser** [ember-cli/ember-ajax#70]
See https://github.com/ember-cli/ember-ajax/blob/master/addon/ajax-request.js#L236

Why are trailing slashes removed?
Right now to keep the trailing slashes in pathes we must convert paths to absolute urls, which feels just not right.

**Comment by alexlafroscia** [comment]
Currently, that's just done for convenience on our part.  You have an API that requires a slash at the end?

**Comment by badazz91** [comment]
Our custom API reacts somewhat opinionated, when forgetting the trailing slashes, resolving in a 404 error.

**Comment by topaxi** [comment]
I just ran into this, I'm encountering an API which does a redirect from non-slashed endpoint to an endpoint with an slash and messes up the response.

**Comment by alexlafroscia** [comment]
Sorry about that; there's a PR open that needs some tweaking before we can fix this. I will try to clean it up myself this week.

**Comment by kaungst** [comment]
One workaround I found was to add an additional trailing slash at the end.
e.g. http://www.random.com/stuff//

**Comment by jamesarosen** [comment]
For posterity: we just fixed this in our app by upgrading to 2.4.1 :)

**Comment by alexlafroscia** [comment]
@jamesarosen excellent! Glad to hear it's working for oyu
