### ISSUE TITLE
Remote url is prefixed with localhost

### ISSUE THREAD

**Issue by Padchi** [ember-cli/ember-ajax#73]
I'm on 2.0.0-beta.2.

`this.get('ajax').request('https//api.github.com/search/')` makes a request to `http://localhost:4200/https//api.github.com/search/`.

**Comment by taras** [comment]
You're missing colon in the url -> 'https://api.github.com/search/'

**Comment by Padchi** [comment]
Haha wow i'm stupid. :+1:
