### ISSUE TITLE
Access to underlying Jquery Request Object ?

### ISSUE THREAD

**Issue by svkangal** [ember-cli/ember-ajax#74]
I have a requirement where I need access to request object so as to cancel the current ongoing request if a new request if fired.

**Comment by svkangal** [comment]
@stefanpenner I see, thanks for the info,

**Comment by stefanpenner** [comment]
> Even with after decoupling the plain native request object can be returned and used to abort right?

well, we hope to swap out to `fetch` once its ready, so unsure..

**Comment by svkangal** [comment]
Cool, Thanks. Closing the issue.
