### ISSUE TITLE
Upload with feedback

### ISSUE THREAD

**Issue by mbrakken** [ember-cli/ember-ajax#76]
Apologies if this is clarified somewhere, but I've only had time to take a cursory glance at this project and related specs.

I understand that the fetch API will not have any upload progress callbacks since it'll use streams, and that the xhr object used to polyfill future behavior isn't exposed since it won't exist with fetch. I also assume, though haven't verified, that streams are currently not widely supported generally, and are not supported here. 

I have an app that supports upload of large files (eg. wav pcm, flac, etc), and it's important that I can provide feedback on the state of an upload operation.

Currently using ic-ajax, I have a service that defines an xhr object so I can set callbacks on relevant event listeners:
```javascript
_upload(file, url, headers, requestType, callbacks){
    return ajax({
        xhr: function(){
            var xhr = new window.XMLHttpRequest();
            xhr.upload.addEventListener('progress', function(evt){
                if (evt.lengthComputable) {
                    var progress =  Math.round((evt.loaded / evt.total)*100);
                    callbacks.upload.progress(progress);
                }
            }, false);
            xhr.upload.addEventListener('load', function(evt){
                callbacks.upload.load(evt);
            }, false);
            // etc
        },
        contentType : fileType,
        url         : url,
        type        : requestType,
        headers     : headers,
        data        : file,
        processData : false,
        dataType    : 'json'
    });
}
```
Since ember ajax initially provided swap out support for ic-ajax, does it offer some means to support similar behavior, or do I need to switch to using `$.ajax` for upload if I want to migrate to ember ajax?

**Comment by alexlafroscia** [comment]
You _should_ be able to do the same thing using `ember-ajax/request` -- that is provided to be a drop-in replacement for `ic-ajax`.  Did you give that a shot?

**Comment by alexlafroscia** [comment]
I'm going to close this for now, since uploading with feedback isn't something we really intend to support.  I wish I had a better answer but we've decided to keep the API as `fetch`-compliant as we can, since the long-term goals are to leverage that instead of jQuery.

If uploading with feedback is required, I'd suggest just using `$.ajax` directly for that request.
