### ISSUE TITLE
Integrate with Ember Data out of the box

### ISSUE THREAD

**Issue by wagenet** [ember-cli/ember-ajax#85]
Right now, unless there's something I've missed, there's no default way to have the ajax service used by Ember Data. As a result, I had to do a work-around like this to avoid duplication:

``` js
// app/adapters/application.js
import Ember from 'ember';
import ActiveModelAdapter from 'active-model-adapter';

const { inject } = Ember;
const { alias } = Ember.computed;

export default ActiveModelAdapter.extend({
  ajaxService: inject.service('ajax'),

  headers: alias('ajaxService.headers')
});
```

It would be awesome for this to happen automatically.

**Comment by taras** [comment]
Totally agree. 

There is an [open issue in Ember Data repo](https://github.com/emberjs/data/issues/4175) and we're hopefully going to start working on this shortly.

**Comment by alexlafroscia** [comment]
I don't think this will ever happen, especially as Ember moves away from `jQuery` as a dependency.

In that world, `ember-ajax` will be an easy way to add `jQuery` only if you want to use `$.ajax`, and even will be a means for importing a custom, slimmed-down build of `jQuery` with only the networking code.

I'm going to close this issue as I don't see it ever actually happening.

**Comment by taras** [comment]
👍
