### ISSUE TITLE
Add isAjaxError helper?

### ISSUE THREAD

**Issue by jaswilli** [ember-cli/ember-ajax#90]
I'm updating some projects to use the new `is*` error helper functions and there are some cases where I don't care at all what specific `AjaxError` came back, just knowing that it's an `AjaxError` is enough.

For consistency, does it make sense to add an `isAjaxError()` helper as well? Otherwise it will be necessary to do a mix of `instanceof` checks and `is*` checks. It seems cleaner if everything could be handled with the helpers.

**Comment by alexlafroscia** [comment]
Yeah, that probably makes sense...

I'm sorta on the fence about the `is*` error helpers as a whole, to be honest.  If the library is going to abstract away the error codes and `reject` the promises with our own error classes... Is the `is*` helper _really_ better than an `instanceof` check?  I kind of like the idea that we can use regular old JavaScript to check the error types.  The additional abstraction seems sorta silly to me, but they predate my involvement with the project and come from the original code that was pulled out of Ember Data.

I would love some feedback from people that are using `ember-ajax` in projects about whether the `is*` helpers are actually useful.  However, if the consensus is that they are really a benefit to the project, I agree that a general-purpose `isAjaxError` helper makes sense to add.

**Comment by taras** [comment]
`is*` helpers will enable us to handle the transition from Ember Data + Ember Ajax to EmberData consuming Ember Ajax. 

They also simplify dealing with errors being reported in different ways. For example, statusCode being a string or an integer. They also make it easier to find all of the places where checking for a particular error. 

`isAjaxError` is probably a good idea.
