### ISSUE TITLE
Doesn't work unless in pods

### ISSUE THREAD

**Issue by optikalefx** [ember-cli/ember-ajax#91]
If I'm extending this service in my own app inside of app/services/ajax.js I get the following warning

```
DEPRECATION: In Ember 2.0 service factories must have an `isServiceFactory` property set to true. You registered [object Object] as a service factory.
```

And then when trying to use `this.get('ajax').request('...')` I get this error

```
ember.debug.js:28601 Error while processing route: holding Failed to create an instance of 'service:ajax'. Most likely an improperly defined class or an invalid module export. Error: Failed to create an instance of 'service:ajax'. Most likely an improperly defined class or an invalid module export.
```

Note that everything works fine with no errors if the service is inside `pods/ajax/service.js`

My service extension

```
import AjaxService from 'ember-ajax/services/ajax';
import config from 'mp3car-ember/config/environment';

export default AjaxService.extend({
});
```

My usage inside a route

```
import Ember from 'ember';

export default Ember.Route.extend({
	ajax: Ember.inject.service(),
	title: 'Holding Page',
	model() {
		let res = this.get('ajax').request('getHoldingPalets');
		console.log('res', res);
		return res;
	}
});
```

Using 

```
ember-cli: 2.4.3
node: 5.9.1
os: darwin x64
ember: 
"ember-ajax": "0.7.1"
```

**Comment by taras** [comment]
Can you please try the ember-ajax 2.0 that was released this weekend? 

(I suspect that it will not fix the problem but I just want to eliminate that first)

**Comment by optikalefx** [comment]
Wow. You led me the answer. I was deleted the contents of pods/ajax/service.js to paste and test into app/services/ajax.js and it was because of the empty file.

I wonder if Ember should have a warning for empty file instead of working through misleading errors.

**Comment by taras** [comment]
Ember has a message like that for modules inside of /app directory but I'm not sure how that's applied. Glad you got it figured out.
