### ISSUE TITLE
Could not find module `ember-mixinify-class`

### ISSUE THREAD

**Issue by andrewhavens** [ember-cli/ember-ajax#94]
I just upgraded to version 2.0.1 (from 0.7.1) by running `ember install ember-ajax`. Now I am getting the error: 

    Could not find module `ember-mixinify-class` imported from `ember-ajax/services/ajax`

Is there an additional dependency that is not specified?

**Comment by taras** [comment]
Try deleting your `node_modules` and run `npm install` again.

**Comment by spruce** [comment]
Thanks @taras that fixed it for me.
