### ISSUE TITLE
query params being serialized into one big object

### ISSUE THREAD

**Issue by jamesdixon** [ember-cli/ember-ajax#99]
Hi, 

I'm running into an issue where my query params are being stringified into one big object. Here's my code:

```javascript
      this.get('ajax').request('/appointments', {
          data: {
            startDate: start.toISOString(),
            endDate: end.toISOString()
          }
        })
        ...
```
And the URL being generated looks like: `/appointments?{%22startDate%22:%222016-03-27%22,%22endDate%22:%222016-05-08%22}`

Am I doing something wrong here?

Thanks!

**Comment by taras** [comment]
`request` method defaults to `GET` type when another type is not specified. 

You could use the `this.get('ajax').post('/appointments, { data: { } })`.

**Comment by jamesdixon** [comment]
Thanks for the reply.

I intended to do a `GET` request with query parameters, not a `POST`.

**Comment by taras** [comment]
Oh, I see what you mean.

**Comment by jamesdixon** [comment]
@taras I believe this line is the culprit: https://github.com/ember-cli/ember-ajax/blob/master/addon/ajax-request.js#L78

**Comment by jamesdixon** [comment]
JSON API is my default `content-type`, which is causing that line to fire and stringify the data. If were to check `requestData.type` for `GET` and ignore it, that could resolve the issue.

**Comment by taras** [comment]
Right, I see what you mean. Would you like to submit a PR? (I'll merge it in)

**Comment by jamesdixon** [comment]
Will do. Thanks!

**Comment by taras** [comment]
Thank you :)

**Comment by taras** [comment]
2.3.1 published 

Thank you 👍

**Comment by jamesdixon** [comment]
Thanks for the quick merge!
